// Code generated by MockGen. DO NOT EDIT.
// Source: ./controllers/nodetool/nodetool.go

// Package nodetool is a generated GoMock package.
package nodetool

import (
	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/ibm/cassandra-operator/api/v1alpha1"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// RepairKeyspace mocks base method
func (m *MockClient) RepairKeyspace(cc *v1alpha1.CassandraCluster, keyspace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepairKeyspace", cc, keyspace)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepairKeyspace indicates an expected call of RepairKeyspace
func (mr *MockClientMockRecorder) RepairKeyspace(cc, keyspace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepairKeyspace", reflect.TypeOf((*MockClient)(nil).RepairKeyspace), cc, keyspace)
}
