{
 "title": "Cassandra Cluster Overview",
 "description": "A cluster-wide overview that's designed for multi-DC topologies",
 "tags": [
  "cassandra",
  "cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(cassandra_endpoint_active, cassandra_cluster)"
   },
   {
    "name": "datacenter",
    "label": "Data Center",
    "query": "label_values(cassandra_endpoint_active{cassandra_cluster=\"$cluster\"}, cassandra_datacenter)"
   },
   { "name": "topn", "label": "Top 𝑛", "query": "5,10,20" },
   { "name": "node_dashboard_url", "query": "/d/WZGSOV8mk/node-overview" }
  ]
 },
 "panels": [
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Cluster Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cassandra_endpoint_active{cassandra_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Current Storage Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_storage_load_bytes{cassandra_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Schema (exc. system keyspaces)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "count(count(cassandra_table_disk_space_bytes{cassandra_cluster=\"$cluster\",keyspace!~\"system.*\"}) by (keyspace))",
     "legendFormat": "Keyspaces"
    },
    {
     "expr": "count(count(cassandra_table_disk_space_bytes{cassandra_cluster=\"$cluster\",keyspace!~\"system.*\",table_type=\"table\"}) by (table)) or vector(0)",
     "legendFormat": "Tables"
    },
    {
     "expr": "count(count(cassandra_table_disk_space_bytes{cassandra_cluster=\"$cluster\",keyspace!~\"system.*\",table_type=\"view\"}) by (table)) or vector(0)",
     "legendFormat": "Materialized Views"
    },
    {
     "expr": "count(count(cassandra_table_disk_space_bytes{cassandra_cluster=\"$cluster\",keyspace!~\"system.*\",table_type=\"index\"}) by (table)) or vector(0)",
     "legendFormat": "Indexes"
    }
   ]
  },
  {
   "title": "Average Cluster Availability for Period",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(cassandra_endpoint_active{cassandra_cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "$cluster Data Centers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Data Center \"$datacenter\"",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "repeat": "datacenter",
   "targets": [
    {
     "expr": "avg(cassandra_endpoint_active{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}) by (cassandra_node)",
     "legendFormat": "{{cassandra_node}}"
    }
   ]
  },
  {
   "title": "Data Center \"$datacenter\"",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(cassandra_endpoint_active{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}) by (cassandra_node)",
     "legendFormat": "{{cassandra_node}}"
    }
   ]
  },
  {
   "title": "Client Requests/s ($datacenter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "repeat": "datacenter",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\", operation=~\"read|rangeslice\"}[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\", operation=~\"write|viewwrite\"}[1m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Client Requests/s ($datacenter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\", operation=~\"read|rangeslice\"}[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\", operation=~\"write|viewwrite\"}[1m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Top $topn Worst Performing Nodes by Client Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Top $topn Nodes by Max p95 Client Read Latency",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "repeat": "datacenter",
   "targets": [
    {
     "expr": "topk($topn,max_over_time(max(cassandra_client_request_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\", operation=~\"read|rangeslice\", quantile=\"0.95\"}) by (cassandra_rack, cassandra_node)[$__range:]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by Max p95 Client Read Latency",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "topk($topn,max_over_time(max(cassandra_client_request_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\", operation=~\"read|rangeslice\", quantile=\"0.95\"}) by (cassandra_rack, cassandra_node)[$__range:]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by Max p95 Client Write Latency",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "repeat": "datacenter",
   "targets": [
    {
     "expr": "topk($topn,max_over_time(max(cassandra_client_request_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\", operation=~\"write|viewwrite\", quantile=\"0.95\"}) by (cassandra_rack, cassandra_node)[$__range:]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by Max p95 Client Write Latency",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "topk($topn,max_over_time(max(cassandra_client_request_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\", operation=~\"write|viewwrite\", quantile=\"0.95\"}) by (cassandra_rack, cassandra_node)[$__range:]))"
    }
   ]
  },
  {
   "title": "Top $topn Worst Performing Nodes by OS Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Top $topn Nodes by Disk Usage",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "repeat": "datacenter",
   "targets": [
    {
     "expr": "topk($topn,max_over_time(((cassandra_storage_filesystem_bytes_total{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"} - cassandra_storage_filesystem_usable_bytes{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}) / cassandra_storage_filesystem_bytes_total{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"})[$__range:]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by Disk Usage",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "topk($topn,max_over_time(((cassandra_storage_filesystem_bytes_total{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"} - cassandra_storage_filesystem_usable_bytes{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}) / cassandra_storage_filesystem_bytes_total{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"})[$__range:]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by Host CPU Usage",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "repeat": "datacenter",
   "targets": [
    {
     "expr": "topk($topn,max_over_time(cassandra_os_recent_cpu_load_ratio{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by Host CPU Usage",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "topk($topn,max_over_time(cassandra_os_recent_cpu_load_ratio{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by 1 Minute Load Average",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "repeat": "datacenter",
   "targets": [
    {
     "expr": "topk($topn,max_over_time(cassandra_os_1m_load_average{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by 1 Minute Load Average",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "topk($topn,max_over_time(cassandra_os_1m_load_average{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Top $topn Worst Performing Nodes by Internode Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 }
  },
  {
   "title": "Top $topn Nodes by Hints in Progress/s",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "repeat": "datacenter",
   "targets": [
    {
     "expr": "topk($topn,max_over_time(rate(cassandra_storage_hints_total{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}[1m])[$__range:]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by Hints in Progress/s",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "topk($topn,max_over_time(rate(cassandra_storage_hints_total{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}[1m])[$__range:]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by Dropped Messages/s",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "repeat": "datacenter",
   "targets": [
    {
     "expr": "topk($topn,max_over_time(sum(irate(cassandra_dropped_messages_total{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}[1m])) by (cassandra_node, cassandra_rack)[$__range:]))"
    }
   ]
  },
  {
   "title": "Top $topn Nodes by Dropped Messages/s",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "topk($topn,max_over_time(sum(irate(cassandra_dropped_messages_total{cassandra_cluster=\"$cluster\", cassandra_datacenter=\"$datacenter\"}[1m])) by (cassandra_node, cassandra_rack)[$__range:]))"
    }
   ]
  }
 ]
}