{
 "title": "Cassandra Instaclustr - Table Details",
 "tags": [
  "cassandra",
  "instaclustr"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cassandra_endpoint_active, cassandra_cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(cassandra_endpoint_active{cassandra_cluster=\"$cluster\"}, cassandra_node)"
    }
   },
   {
    "name": "table_type",
    "label": "Type",
    "query": {
     "query": "label_values(cassandra_table_disk_space_bytes{cassandra_cluster=\"$cluster\"}, table_type)"
    }
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(cassandra_table_disk_space_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", table_type=~\"$table_type\"}, keyspace)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(cassandra_table_disk_space_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table_type=~\"$table_type\"}, table)"
    }
   },
   {
    "name": "operation",
    "query": "read,write,range_read,cas_propose,cas_prepare,cas_commit"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage (inc. obsolete SSTables pending GC)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_disk_space_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Live Disk Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_live_disk_space_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Snapshot Disk Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_snapshots_size_bytes_total{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Live SSTables",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "SSTables" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_live_sstables{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Engine Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ops/s ($operation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
     "repeat": "operation",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", operation=\"$operation\"}[1m])",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Mean Latency ($operation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
     "repeat": "operation",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_table_operation_latency_seconds_sum{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", operation=\"$operation\"}[1m]) / irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", operation=\"$operation\"}[1m])",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p50 Latency ($operation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
     "repeat": "operation",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_operation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", operation=\"$operation\", quantile=\"0.5\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p75 Latency ($operation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
     "repeat": "operation",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_operation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", operation=\"$operation\", quantile=\"0.75\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p95 Latency ($operation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
     "repeat": "operation",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_operation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", operation=\"$operation\", quantile=\"0.95\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p99 Latency ($operation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 42 },
     "repeat": "operation",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_operation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", operation=\"$operation\", quantile=\"0.99\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Estimated Rows Per Partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50 Estimated Rows per Partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short", "label": "Rows" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_estimated_columns{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.5\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p75 Estimated Rows per Partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
     "yaxes": [
      { "format": "short", "label": "Rows" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_estimated_columns{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.75\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p95 Estimated Rows per Partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short", "label": "Rows" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_estimated_columns{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.95\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p99 Estimated Rows per Partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
     "yaxes": [
      { "format": "short", "label": "Rows" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_estimated_columns{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SSTables Per Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50 SSTables Per Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "SSTables" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_sstables_per_read{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.5\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p75 SSTables Per Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "SSTables" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_sstables_per_read{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.75\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p95 SSTables Per Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "SSTables" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_sstables_per_read{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.95\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p99 SSTables Per Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "SSTables" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_sstables_per_read{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Estimated Partition Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50 Estimated Partition Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_estimated_partition_size_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.5\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p75 Estimated Partition Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_estimated_partition_size_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.75\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p95 Estimated Partition Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_estimated_partition_size_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.95\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p99 Estimated Partition Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_estimated_partition_size_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tombstones Scanned Per Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50 Tombstones Scanned Per Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Tombstones" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_tombstones_scanned{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.5\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p75 Tombstones Scanned Per Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_tombstones_scanned{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.75\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p95 Tombstones Scanned Per Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_tombstones_scanned{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.95\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "p99 Tombstones Scanned Per Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_tombstones_scanned{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", quantile=\"0.99\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compression",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compression Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_compression_ratio{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Compression Metadata Off-Heap Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_compression_metadata_offheap_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Key Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_key_cache_hit_ratio{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Row Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_row_cache_hits{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"} / (cassandra_table_row_cache_hits{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"} + cassandra_table_row_cache_misses{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"})",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memtable Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memtable Off-heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_memory_used_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", pool=\"memtable\", region=\"off_heap\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Memtable On-heap Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_memory_used_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", pool=\"memtable\", region=\"on_heap\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Memtable Live Data Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_memtable_live_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Memtable Switches/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Switches" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_table_memtable_switches{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}[1m])",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Memtable Columns",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Columns" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_memtable_columns{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated Pending Compactions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Compactions" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_estimated_pending_compactions{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Compaction Bytes Written/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_table_compaction_bytes_written_total{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}[5m])",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bloom Filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bloom Filter Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_memory_used_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", pool=\"bloom_filter\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Bloom Filter Disk Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_bloom_filter_disk_space_used_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Bloom Filter False Positives/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "False Positives" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_table_bloom_filter_false_positives_total{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}[5m])",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Bloom Filter False Positives Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_bloom_filter_false_ratio{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Flushes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Flushes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_pending_flushes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Bytes Flushed/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_table_flushed_bytes_total{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}[5m])",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Index Summary Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_memory_used_bytes{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\", pool=\"index_summary\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Repaired Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_repaired_ratio{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Estimated Partitions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short", "label": "Partitions" }
     ],
     "targets": [
      {
       "expr": "cassandra_table_estimated_partitions{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Speculative Retries/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_table_speculative_retries_total{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}[5m])",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Dropped Mutations/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_table_dropped_mutations_total{cassandra_cluster=\"$cluster\", cassandra_node=~\"$node\", keyspace=\"$keyspace\", table=~\"$table\"}[5m])",
       "legendFormat": "{{table}}/{{cassandra_node}}"
      }
     ]
    }
   ]
  }
 ]
}