{
 "title": "Cassandra - Client Connections",
 "tags": [
  "tlp",
  "cassandra",
  "beta"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "label_values(org_apache_cassandra_metrics_Storage_Load, namespace)"
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(org_apache_cassandra_metrics_Storage_Load, environment)"
   },
   {
    "name": "instance",
    "query": "label_values(org_apache_cassandra_metrics_Storage_Load,app_kubernetes_io_name)"
   },
   {
    "name": "dc",
    "label": "Data Center",
    "query": "label_values(org_apache_cassandra_metrics_Storage_Load, datacenter)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(org_apache_cassandra_metrics_Storage_Load, host)"
   }
  ]
 },
 "panels": [
  { "title": "Client Connections Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections (per host)",
   "type": "graph",
   "description": "The number of connected clients to each Cassandra node. Plots both native and Thrift protocol connections if available. Since Cassandra 2.2, Thrift connections are not opened by default.\n\n##### Values\n\nA Cassandra node supports up to 128 connections per node. Values above 128 are not to be expected.\n\nIt is important, however, that there is a balanced number of connections  among the nodes.\n\n##### False Positives\n\nThis metric is pretty straightforward and should not fluctuate unexpectedly.\n\n##### Required Actions\n\nIf the number of connections approaches 128 per node, the client connection options and the load balancing strategy need to be revised.\n\n##### Warning\n\nNot balanced number of connections needs to be acted on.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Client connections" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_Client_connectedNativeClients{environment=\"$env\", datacenter=\"$dc\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.connectedNativeClients",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.Client.connectedNativeClients.value, 3, 9)"
    },
    {
     "expr": "org_apache_cassandra_metrics_Client_connectedThriftClients{environment=\"$env\", datacenter=\"$dc\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.connectedThriftClients",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.Client.connectedThriftClients.value, 3, 9)"
    }
   ]
  },
  {
   "title": "Connections (per data center)",
   "type": "graph",
   "description": "Number of client connections summed per data cetnter.\n\n##### Values\n\nAbsolute values depend on the number of nodes per data center.\n\n##### False Positives\n\nIt is possible to have significant differences among sum of connections to each data center. This can happen in situations when different data centers serve different cohorts of clients having peak load happening at different times.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Client connections" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Client_connectedNativeClients{environment=\"$env\", datacenter=\"$dc\"}) by (environment, datacenter)",
     "legendFormat": "{{environment}}.{{datacenter}}.connectedNativeClients",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.Client.connectedNativeClients.value, 3), 2, 8)"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_Client_connectedThriftClients{environment=\"$env\", datacenter=\"$dc\"}) by (environment, datacenter)",
     "legendFormat": "{{environment}}.{{datacenter}}.connectedThriftClients",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.Client.connectedThriftClients.value, 3), 2, 8)"
    }
   ]
  },
  {
   "title": "Timeouts (per host)",
   "type": "graph",
   "description": "A Cassandra client typically interacts with the cluster via a coordinator node, which is responsible for arranging the operation to be carried out.\n\nIf the operation takes too long the coordinator will time out the operation. This graph shows a rate of the timeouts happening per node.\n\n##### Values\n\nThis graph shows a per-minute rate of timeouts happening on each node, further broken down by the operation type.\n\n##### False Positives\n\nTimeouts should not happen under any circumstances. There are no false positives.\n\n##### Required Actions\n\nIf timeouts happen, their cause needs to be investigated. The top-level reasons for timeouts occurring include over-loaded nodes, misconfigured clients or ill-fitting data model (including sub-optimal queries).\n\n##### Warning\n\nTimeouts might percolate all the way to application level, where they can cause SLA degradation.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops", "label": "Timeouts" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_ClientRequest_Timeouts{environment=\"$env\", datacenter=\"$dc\", unit=\"OneMinuteRate\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{scope}}.m1",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.*.Timeouts.1MinuteRate, 3, 9)"
    }
   ]
  },
  {
   "title": "Timeouts (per data center)",
   "type": "graph",
   "description": "Similar to `Timeouts (per host)` graph, with the difference that this graph sums the timeouts per data center.\n\nThe purpose of this graph is to provide insight if it is isolated nodes having problems, or if the problem is more wide-spread.\n\n##### Values\n\nAmount of timeouts happening in each datacenter per minute, further split among each operation type.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops", "label": "Timeouts" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Timeouts{environment=\"$env\", datacenter=\"$dc\", unit=\"OneMinuteRate\"}) by (environment, datacenter, scope)",
     "legendFormat": "{{environment}}.{{datacenter}}.{{scope}}.m1",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.*.Timeouts.1MinuteRate, 3), 2, 8)"
    }
   ]
  },
  {
   "title": "Unavailables (per host)",
   "type": "graph",
   "description": "A Cassandra client typically interacts with the cluster via a coordinator node, which is responsible for arranging the operation to be carried out.\n\nFor certain operations, the coordinator needs responses from multiple nodes. If the coordinator can not possibly obtain responses from these nodes, an `Unavailable` error occurs.\n\nFor example, in a cluster with replication factor of three and two replicas down for a given partition, executing an operation with a `QUORUM` consistency will trigger an `Unavailable` error.\n\n##### Values\n\nThe values are a per-second rate of `Unavailable` errors occurring per node, further broken down by operation type.\n\n##### False Positives\n\nFalse positives should not happen.\n\nHowever, sometimes the cause of `Unavailable` errors is a discrepancy between keyspace topology and consistency used by the application. \n\n##### Required Actions\n\n`Unavailable` errors should not happen in clusters. If they do, they cause needs to be investigated and promptly addressed.\n\n##### Warning\n\n`Unavailable` errors can be a symptom of down nodes. Down nodes are generally a bad thing and should be investigated and promptly fixed.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops", "label": "Unavailable errors" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_ClientRequest_Unavailables{environment=\"$env\", datacenter=\"$dc\", unit=\"OneMinuteRate\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{scope}}.m1",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.*.Unavailables.1MinuteRate, 3, 9)"
    }
   ]
  },
  {
   "title": "Unavailables (per data center)",
   "type": "graph",
   "description": "Similar to `Unavailables (per host)`, this graph shows the number of `Unavailable` errors occurring in the cluster, but sums the errors by data center.\n\n##### Values\n\nThe values are the number of `Unavailaber` errors happening per minute in each data center, further broken down by operation type.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops", "label": "Unavailable errors" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_ClientRequest_Unavailables{environment=\"$env\", datacenter=\"$dc\", unit=\"OneMinuteRate\"}) by (environment, datacenter, scope)",
     "legendFormat": "{{environment}}.{{datacenter}}.{{scope}}.m1",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.*.Unavailables.1MinuteRate, 3), 2, 8)"
    }
   ]
  },
  { "title": "Thread Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Native Requests Pool (per host)",
   "type": "graph",
   "description": "Cassandra groups task of a particular type to its own thread pool. Monitoring thread pools is important to understand the saturation of the node.\n\nIn this graph, a thread pool responsible for handling client CQL requests is shown.\n\n##### Values\n\nThe values are the current number of tasks in a particular state. The states tracked are:\n* **Active**: tasks actively worked on.\n* **Pending**: queued tasks.\n* **Blocked**: tasks blocked due to queue saturation. \n\n##### False Positives\n\nIt is acceptable for the `Pending` and `Blocked` tasks to have non-zero value.\n\n##### Required Actions\n\nIn case of sharp increase, or constant values in order of several tens, node capacity assessment needs to happen.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_ThreadPools{environment=\"$env\", datacenter=\"$dc\", status_pool=\"ActiveTasks\", thread_type=\"transport\", thread_pool=\"Native-Transport-Requests\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.transport.Native-Transport-Requests.ActiveTasks.value, 3, 11)"
    },
    {
     "expr": "org_apache_cassandra_metrics_ThreadPools{environment=\"$env\", datacenter=\"$dc\", status_pool=\"PendingTasks\", thread_type=\"transport\", thread_pool=\"Native-Transport-Requests\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.transport.Native-Transport-Requests.PendingTasks.value, 3, 11)"
    },
    {
     "expr": "org_apache_cassandra_metrics_ThreadPools{environment=\"$env\", datacenter=\"$dc\", status_pool=\"CurrentlyBlockedTasks\", thread_type=\"transport\", thread_pool=\"Native-Transport-Requests\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.transport.Native-Transport-Requests.CurrentlyBlockedTasks.value, 3, 11)"
    }
   ]
  },
  {
   "title": "Coordinator Requests Pool (per host)",
   "type": "graph",
   "description": "Cassandra groups task of a particular type to its own thread pool. Monitoring thread pools is important to understand the saturation of the node.\n\nThis thread pool handles coordinator requests to the cluster.\n\n##### Values\n\nThe values are the current number of tasks in a particular state. The states tracked are:\n\n* **Active**: tasks actively worked on.\n* **Pending**: queued tasks.\n* **Blocked**: tasks blocked due to queue saturation.\n\n##### False Positives\n\nIt is acceptable for the `Pending` and `Blocked` tasks to have non-zero value.\n\n##### Required Actions\n\nIn case of sharp increase, or constant values in order of several tens, node capacity assessment needs to happen.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_ThreadPools{environment=\"$env\", datacenter=\"$dc\", status_pool=\"ActiveTasks\", thread_type=\"request\", thread_pool=\"RequestResponseStage\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.request.RequestResponseStage.ActiveTasks.value, 3, 11)"
    },
    {
     "expr": "org_apache_cassandra_metrics_ThreadPools{environment=\"$env\", datacenter=\"$dc\", status_pool=\"PendingTasks\", thread_type=\"request\", thread_pool=\"RequestResponseStage\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.request.RequestResponseStage.PendingTasks.value, 3, 11)"
    },
    {
     "expr": "org_apache_cassandra_metrics_ThreadPools{environment=\"$env\", datacenter=\"$dc\", status_pool=\"CurrentlyBlockedTasks\", thread_type=\"request\", thread_pool=\"RequestResponseStage\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.request.RequestResponseStage.CurrentlyBlockedTasks.value, 3, 11)"
    }
   ]
  },
  { "title": "Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Prepared Statements Cache (by host)",
   "type": "graph",
   "description": "Cassandra allows server-side caching of CQL queries to avoid their repetitive parsing, which yields certain performance benefits.\n\nThis graph shows the number of statements cached. \n\n##### Values\n\nThe values are a number of cached statements per node. The exact value of the statements in cache varies, because the the cache size is configured (since Cassandra 3.6) in bytes, rather than statement counts.\n\n##### False Positives\n\nMonotonic values in orders of hundreds can signal saturated cache. However, this situation needs to be correlated with the `Prepared Statements Eviction` graph to prove the saturation.\n\n##### Required Actions\n\nIt is unlikely the application actually needs the whole cache. If the saturation happens, it's typically a sign of repetitive statement preparation, which is sub-optimal.\n\n##### Warning\n\nSaturated prepared statements cache signals misuse on the application level, which should be corrected.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Statements" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_CQL_PreparedStatementsCount{environment=\"$env\", datacenter=\"$dc\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.PreparedStatementsCount",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.CQL.PreparedStatementsCount.value, 3)"
    }
   ]
  },
  {
   "title": "Prepared Statements Eviction (by host, perSecond() issues)",
   "type": "graph",
   "description": "Cassandra allows server-side caching of CQL queries to avoid their repetitive parsing, which yields certain performance benefits.\n\nThis graph shows the eviction of prepared statements from their cache.\n\n##### Values\n\nThe values represent the number of statements evicted per second per node.\n\n##### False Positives\n\nIt is acceptable for a Cassandra node to evict some statements. This should happen sporadically, and exclusively after operator-triggered operations.\n\n##### Required Actions\n\nPrepared statement eviction occurring signals misuse at the application level which needs to be investigated and remedied.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ops", "label": "Eviction rate" }
   ],
   "targets": [
    {
     "expr": "deriv(org_apache_cassandra_metrics_CQL_PreparedStatementsEvicted{environment=\"$env\", datacenter=\"$dc\"}[5m])",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.PreparedStatementsEvicted",
     "target": "aliasByNode(perSecond(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.CQL.PreparedStatementsEvicted.count), 3)"
    }
   ]
  },
  {
   "title": "Prepared vs Unprepared (by host)",
   "type": "graph",
   "description": "This graph shows the ratio between prepared and regular statements executed.\n\n##### Values\n\nThe closer to `1.0` the value, the bigger the portion of prepared statements executed.\n\nThe values are reported per each host.\n\n##### Required Actions\n\nBased on the work load, if this ratio swings towards the unexpected type of requests executed, an investigation of the application should ensue.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_CQL_PreparedStatementsRatio{environment=\"$env\", datacenter=\"$dc\"}",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.PreparedStatementsRatio",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.CQL.PreparedStatementsRatio.value, 3)"
    }
   ]
  },
  {
   "title": "Regular Statements Executed (by host, perSecond() issues)",
   "type": "graph",
   "description": "Unlike prepared statements, the regular statements need to be parsed every time they are executed. Because of this, they might not be desired if performance is critical.\n\n##### Values\n\nCassandra reports only the total number of regular statements executed over its uptime. Therefore we're using Grafana's `perSecond()` aggregation to visualise a per-second rate of regular statement execution per host.\n\n##### False Positives\n\nRegular statements are sometimes inevitable. For example, the java-driver performs several regular statements upon initialising its connection in order to learn the cluster topology etc.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ops", "label": "Statement rate" }
   ],
   "targets": [
    {
     "expr": "deriv(org_apache_cassandra_metrics_CQL_RegularStatementsExecuted{environment=\"$env\", datacenter=\"$dc\"}[5m])",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.RegularStatementsExecuted",
     "target": "aliasByNode(perSecond(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.CQL.RegularStatementsExecuted.count), 3)"
    }
   ]
  },
  { "title": "Client Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "LWT Problems (by host, perSecond() issues)",
   "type": "graph",
   "description": "Cassandra exposes certain metrics related Light-Weight Transactions (LWT) that might indicate problems:\n* **ConditionNotMet**: indicates a failure to meet a condition requested by the transaction. This might indicate a contention in modifying a single cell.\n* **UnfinishedCommit** indicates premature conclusions of Paxos rounds, which is mundane by itself and has mundane consequences too.\n\n##### Values\n\nThe values are per-second rates of both problematic behaviours occurring, broken down per node and per LWT type (read or write).\n\n##### False Positives\n\nIt is acceptable for these metrics to be non-zero if their values are small and happen infrequently.\n\n##### Required Actions\n\nIn case the values are constantly non-zero, the use-case needs to revised as it might be designed in a sub-optimal way.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "deriv(org_apache_cassandra_metrics_ClientRequest_ConditionNotMet{environment=\"$env\", datacenter=\"$dc\"}[5m])",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{scope}}.ConditionNotMet",
     "target": "aliasByNode(perSecond(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.*.ConditionNotMet.count), 3, 9, 10)"
    },
    {
     "expr": "deriv(org_apache_cassandra_metrics_ClientRequest_UnfinishedCommit{environment=\"$env\", datacenter=\"$dc\"}[5m])",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{scope}}.UnfinishedCommit",
     "target": "aliasByNode(perSecond(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.*.UnfinishedCommit.count), 3, 9, 10)"
    }
   ]
  },
  {
   "title": "Total Latency (possible derivative() issues)",
   "type": "graph",
   "description": "Cassandra tracks total latency accumulated while carrying out a particular request. This happens on the coordinator level and represents the total time the request has spent in the cluster.\n\n##### Values\n\nCassandra reports an ever-raising value representing microseconds spent. For visualisation we are using Grafana's derivative to gauge any trends.\n\n##### Required Actions\n\nTrend changes in the values shown in these graphs indicate the subtle degradations that can happen in a Cassandra cluster and should trigger an investigation.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "deriv(org_apache_cassandra_metrics_ClientRequest_TotalLatency[5m])",
     "legendFormat": "{{environment}}.{{datacenter}}.{{host}}.{{scope}}",
     "target": "aliasByNode(derivative(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.*.TotalLatency.count), 3, 9)"
    }
   ]
  }
 ]
}