{
 "title": "Cassandra TLP - Overview",
 "tags": [
  "cassandra",
  "tlp"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load, namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load,app_kubernetes_io_name)"
    }
   },
   {
    "name": "dc",
    "label": "Data Center",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load{app_kubernetes_io_name=\"$instance\"}, datacenter)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load{datacenter=~\"$dc\", app_kubernetes_io_name=\"$instance\"}, host)"
    }
   },
   {
    "name": "pod",
    "label": "Host",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load{datacenter=~\"$dc\", app_kubernetes_io_name=\"$instance\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Alive Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node status (Gossip)",
   "type": "table-old",
   "description": "Gossip messages are exchanged with other nodes as long as the node is up and able to communicate properly through port 7000 (or 7001 secured).\n\n##### Values\n\nA value of `1` is displayed if the number of processed Gossip messages has changed recently.\n\nA value of `0` is displayed if the number of processed gossip messages has not changed recently. If a value of `0` appears, this implies the node may be offline or not communicating properly with other nodes in the cluster.\n\n##### Required Actions\n\nIf Gossip messages are not being processed:\n\n* No incoming Gossip messages are being sent from the other nodes to this Cassandra node.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "rate(org_apache_cassandra_metrics_ThreadPools{namespace=\"$ns\", datacenter=\"$dc\", status_pool=\"CompletedTasks\", thread_type=\"internal\", thread_pool=\"GossipStage\"}[2m])",
     "legendFormat": "{{pod}}",
     "target": "aliasByNode(changed(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ThreadPools.internal.GossipStage.CompletedTasks.value), 3)"
    }
   ]
  },
  {
   "title": "Node status (Native)",
   "type": "table-old",
   "description": "Native requests will be processed if CQL statements are being processed.\n\n##### Values\n\nA value of `1` is displayed if the number of processed Native requests has changed recently.\n\nA value of `0` is displayed if the number of processed Native requests has not changed recently. If a value of `0` appears, this implies the node may be offline or not currently processing any CQL requests.\n\n##### Required Actions\n\nIf Native requests are not being processed:\n\n* No incoming CQL requests are being sent from the application to the Cassandra node.\n* An application update may have removed nodes from the `RoundRobinPolicy`.\n* Only Thrift-based requests are being processed.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(org_apache_cassandra_metrics_ThreadPools{namespace=\"$ns\", datacenter=\"$dc\", status_pool=\"CompletedTasks\", thread_type=\"request\", thread_pool=\"RequestResponseStage\"}[2m])",
     "legendFormat": "{{pod}}",
     "target": "aliasByNode(changed(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ThreadPools.request.RequestResponseStage.CompletedTasks.value), 3)"
    }
   ]
  },
  {
   "title": "Alerting on Gossip",
   "type": "graph",
   "description": "Gossip requests are a natural mechanism within Cassandra for calculating the cluster topography  in a decentralized manner.\n\n##### Values\n\nA value of `1` is displayed if the number of processed Gossip requests has changed recently.\n\nA value of `0` is displayed if the number of processed Gossip requests has not changed recently. If a value of `0` appears, this implies the node may be offline or unable to report its status to the Gossip state.\n\n##### False Positives\n\nA temporary lapse from `1` to `0` may indicate heavier than usual load.\n\nConsider tuning the `phi_convict_threshold` setting to `12` if running in AWS and experiencing issues with flapping nodes that momentarily display the `DN`, or `Downed/Normal`, status via `nodetool status`.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "0 is offline, 1 is online" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_ThreadPools{namespace=\"$ns\", datacenter=\"$dc\", status_pool=\"CompletedTasks\", thread_type=\"internal\", thread_pool=\"GossipStage\"}",
     "target": "aliasByNode(changed(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ThreadPools.internal.GossipStage.CompletedTasks.value), 3)"
    }
   ]
  },
  { "title": "Operational Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "dc" },
  {
   "title": "Read latencies (by data center)",
   "type": "graph",
   "description": "Monitor `p75` latencies to get a view of the cluster's typical operating latencies.\n\nMonitor the `p95` and `p99` latencies for anomalies to get an early indicator for potential issues.\n\n##### Required Actions\n\nIf `p95` read latency metrics spike, investigate:\n\n* Disk contention.\n* Frequent garbage collections.\n* Prolonged garbage collection times.\n* Inefficient read patterns.\n* Back pressure.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs", "label": "Read latency" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$ns\", datacenter=\"$dc\", scope=\"Read\", unit=\"75thPercentile\"}) by (namespace, datacenter, scope)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{scope}}.Latency.p75",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Read.Latency.75percentile, 3), 2, 8, 9, 10)"
    },
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$ns\", datacenter=\"$dc\", scope=\"Read\", unit=\"95thPercentile\"}) by (namespace, datacenter, scope)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{scope}}.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Read.Latency.95percentile, 3), 2, 8, 9, 10)"
    },
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$ns\", datacenter=\"$dc\", scope=\"Read\", unit=\"99thPercentile\"}) by (namespace, datacenter, scope)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{scope}}.Latency.p99",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Read.Latency.99percentile, 3), 2, 8, 9, 10)"
    }
   ]
  },
  {
   "title": "Write latencies (by data center)",
   "type": "graph",
   "description": "Monitor `p75` latencies to get a view of the cluster's typical operating latencies.\n\nMonitor the `p95` and `p99` latencies for anomalies to get an early indicator for potential issues.\n\n##### Required Actions\n\nIf `p95` write latency metrics spike, investigate:\n\n* Disk contention.\n* Counter usage.\n* Lightweight transaction usage.\n* Frequent garbage collections.\n* Prolonged garbage collection times.\n* Back pressure.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "µs", "label": "Write latency" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$ns\", datacenter=\"$dc\", scope=\"Write\", unit=\"75thPercentile\"}) by (namespace, datacenter, scope)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{scope}}.Latency.p75",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Write.Latency.75percentile, 3), 2, 8, 9, 10)"
    },
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$ns\", datacenter=\"$dc\", scope=\"Write\", unit=\"95thPercentile\"}) by (namespace, datacenter, scope)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{scope}}.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Write.Latency.95percentile, 3), 2, 8, 9, 10)"
    },
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$ns\", datacenter=\"$dc\", scope=\"Write\", unit=\"99thPercentile\"}) by (namespace, datacenter, scope)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{scope}}.Latency.p99",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Write.Latency.99percentile, 3), 2, 8, 9, 10)"
    }
   ]
  },
  {
   "title": "Other operations latencies (by data center)",
   "type": "graph",
   "description": "Monitor the `p95` and `p99` latencies for anomalies to get an early indicator for potential issues.\n\n##### Required Actions\n\nIf experiencing issues with this graph, use the additional TLP graphs to detect issues with the specific request type that triggered the alert.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "µs", "label": "Operational latencies" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$ns\", datacenter=\"$dc\", scope!=\"Write\", scope!=\"Read\", unit=\"95thPercentile\"}) by (namespace, datacenter, scope)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{scope}}.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ClientRequest.{CASRead,CASWrite,RangeSlice}.Latency.95percentile, 3), 2, 8, 9, 10)"
    }
   ]
  },
  { "title": "Operation Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "dc" },
  {
   "title": "Read request counts (by data center)",
   "type": "graph",
   "description": "Display the number of read requests by data center.\n\n##### Values\n\nChanges in this graph should match closely with application load.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops", "label": "Read counts" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$ns\", datacenter=\"$dc\", scope=\"Read\", unit=\"OneMinuteRate\"}) by (namespace, datacenter, scope)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{scope}}.Requests.m1",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Read.Latency.1MinuteRate, 3), 2, 8)"
    }
   ]
  },
  {
   "title": "Write request counts (by data center)",
   "type": "graph",
   "description": "Display the number of write requests by data center.\n\n##### Values\n\nChanges in this graph should match closely with application load.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "ops", "label": "Write counts" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$ns\", datacenter=\"$dc\", scope=\"Write\", unit=\"OneMinuteRate\"}) by (namespace, datacenter, scope)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{scope}}.Requests.m1",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ClientRequest.Write.Latency.1MinuteRate, 3), 2, 8)"
    }
   ]
  },
  {
   "title": "Other request counts (by data center)",
   "type": "graph",
   "description": "Display the number of other requests by data center.\n\n##### Values\n\nChanges in this graph should match closely with application load.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "ops", "label": "Other counts" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$ns\", datacenter=\"$dc\", scope!=\"Read\", scope!=\"Write\", unit=\"OneMinuteRate\"}) by (namespace, datacenter, scope)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{scope}}.m1",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ClientRequest.{CASRead,CASWrite,RangeSlice}.Latency.1MinuteRate, 3), 2, 8)"
    }
   ]
  },
  { "title": "Other Important Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "dc" },
  {
   "title": "Dropped messages (by data center)",
   "type": "graph",
   "description": "Display the number of dropped messages per request type, by data center.\n\n##### Values\n\nA ideal value of `0` means that no requests have been dropped.\n\n##### Required Actions\n\nValues higher than `0` indicates an under-provisioned cluster for the specific request types. Under-provisioned clusters often times will experience the following issues that cause dropped messages:\n\n* Frequent garbage collections.\n* Prolonged garbage collection times.\n* Inefficient read patterns.\n* Back pressure.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops", "label": "Dropped messages" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_DroppedMessages_Dropped{namespace=\"$ns\", datacenter=\"$dc\"}) by (namespace, datacenter, message_type)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{message_type}}",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.DroppedMessage.*.Dropped.1MinuteRate, 3), 2, 8)"
    }
   ]
  },
  {
   "title": "Max partition size (by node and table)",
   "type": "graph",
   "description": "This graph displays the `max` size of a partition across all nodes and tables.\n\n##### Values\n\nThe max size of the row must be taken into account when calculating the amount of required heap space.\n\nWhile the maximum number of partition cells (CQL rows x CQL columns) is limited to 2 billion and a single column value is restricted to 2GB, the real-world limitation exists at around 100MB partitions.\n\nOnce partitions grow to more than 100MB:\n\n* Row caching can quickly be busted as a single row can consume all of the allocated row cache heap space.\n* Out of Memory exceptions may occur frequently as a single row may take over the majority of the heap space.\n* CPU and disk load may increase as multiple passes may be needed to load a row into memory.\n* Compactions may cause heap pressure as rows are read into memory before being written to the new SSTables.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(org_apache_cassandra_metrics_Table_MaxRowSize{namespace=\"$ns\", datacenter=\"$dc\"})  by (namespace, datacenter, host, keyspace, table)",
     "target": "aliasByNode(cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.*.*.MaxRowSize.value, 2, 3, 9, 10)"
    }
   ]
  },
  {
   "title": "Pending Compactions (by host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_Table_PendingCompactions{namespace=\"$ns\", datacenter=\"$dc\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.PendingCompactions",
     "target": "cassandra.$ns.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.all.PendingCompactions.value"
    }
   ]
  },
  { "title": "System-Level Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Display all aspects of CPU utilization in a stacked chart to highlight where the CPU is spending the majority of its time.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "CPU utilization" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"$ns\", pod_name=~\"$pod\", container_name=\"cassandra\"}[1m]))",
     "legendFormat": "Current: {{ pod_name}}",
     "target": "aliasByNode(averageSeriesWithWildcards(collectd.$ns.cassandra.$dc.$host.cpu.percent.wait, 4), 1, 4, 6)"
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$ns\", resource=\"cpu\", pod=~\"$pod\", container=\"cassandra\"})",
     "legendFormat": "Requested: {{ $dc }}",
     "target": "aliasByNode(averageSeriesWithWildcards(collectd.$ns.cassandra.$dc.$host.cpu.percent.interrupt, 4), 1, 4, 6)"
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$ns\", resource=\"cpu\", pod=~\"$pod\", container=\"cassandra\"})",
     "legendFormat": "Limit: {{ $dc }}",
     "target": "aliasByNode(averageSeriesWithWildcards(collectd.$ns.cassandra.$dc.$host.cpu.percent.softirq, 4), 1, 4, 6)"
    }
   ]
  },
  {
   "title": "Java: CPU Load",
   "type": "graph",
   "description": "This chart displays:\n\n* Aggregated data center's CPU short term load.\n* Individual node's CPU short term load.\n\n##### Values\n\nIf CPU load is generally high:\n\n* Consider increasing the number of nodes.\n\nIf horizontally scaling the cluster is not an option, consider:\n\n* Lowering encryption requirements.\n* Choose a more powerful CPU per node.\n\n##### Required Actions\n\nIf CPU load is spiking, monitor the number of concurrent compactions.\n\nPossible issues that may cause a spike in CPU load include:\n\n* Garbage collection issues.\n* Non-optimal compaction strategy.\n    * Too many SSTables per read.\n    * Frequent partition updates.\n* Ultra-wide partitions.\n* Client-based connection issues.\n* Secondary Indexes.\n* High frequency page cache-backed reads.\n* CPU interrupt issues.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit", "label": "Short term CPU load" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{namespace=\"$ns\", datacenter=~\"$dc\", pod=~\"$host\"}",
     "legendFormat": "{{pod}}",
     "target": "aliasByNode(averageSeriesWithWildcards(averageSeriesWithWildcards(collectd.$ns.cassandra.$dc.$host.load.load.shortterm, 2), 3), 2, 4, 5)"
    }
   ]
  },
  {
   "title": "Current disk space used (by disk)",
   "type": "bargauge",
   "description": "Display the percentage of `used` disk space:\n\n* Per node.\n* Per monitored directory, as set in `collectd.conf` on the Cassandra nodes.\n\nFree disk space is critical for normal Cassandra operations in order to allow for the compaction of two or more SSTables into a single SSTable.\n\nIn order for this process to occur, there needs to be enough disk space to write out a file no larger than the combined size of all SSTables being compacted. Once the new SSTable is written to disk, the deprecated SSTables will be removed and free disk space should return to a level seen before the compaction was initiated, or lower if mutations were removed from disk during the compaction process.\n\n##### Values\n\nIf a node's data directory is utilizing 65% of the disk's capacity, begin the procurement process to add more nodes to the data center.\n\n##### Required Actions\n\nIf a node's data directory is utilizing 80% of the disk's capacity, bootstrapping a new node should already be underway.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes{namespace=\"$ns\", persistentvolumeclaim=~\"data-([[host]])\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$ns\", persistentvolumeclaim=~\"data-([[host]])\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}}",
     "target": "aliasByNode(sumSeriesWithWildcards(collectd.$ns.cassandra.$dc.$host.df.*.percent_bytes.{reserved,used}, 8), 3, 4, 6)"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "description": "Display the percentage of `used` and `reserved` disk space:\n\n* Per node.\n* Per monitored directory, as set in `collectd.conf` on the Cassandra nodes.\n\nFree disk space is critical for normal Cassandra operations in order to allow for the compaction of two or more SSTables into a single SSTable.\n\nIn order for this process to occur, there needs to be enough disk space to write out a file no larger than the combined size of all SSTables being compacted. Once the new SSTable is written to disk, the deprecated SSTables will be removed and free disk space should return to a level seen before the compaction was initiated, or lower if mutations were removed from disk during the compaction process.\n\n##### Values\n\nIf a node's data directory is utilizing 65% of the disk's capacity, begin the procurement process to add more nodes to the data center.\n\n##### Required Actions\n\nIf a node's data directory is utilizing 80% of the disk's capacity, bootstrapping a new node should already be underway.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent", "label": "Disk utilization" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"$ns\", persistentvolumeclaim=~\"data-([[host]])\"}",
     "legendFormat": "usage.{{persistentvolumeclaim}}",
     "target": "aliasByNode(sumSeriesWithWildcards(collectd.$ns.cassandra.$dc.$host.df.*.percent_bytes.{reserved,used}, 8), 3, 4, 6)"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"$ns\", persistentvolumeclaim=~\"data-([[host]])\"}",
     "legendFormat": "capacity.{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Network Throughput (by data center)",
   "type": "graph",
   "description": "Monitor the network throughput of TX and RX packets.\n\nReceived throughput is displayed as a negative number (downloaded).\n\nTransferred throughput is displayed as a positive number (uploaded).",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps", "label": "Network Throughput" }
   ],
   "targets": [
    {
     "expr": "0 - sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{job=\"kubelet\", namespace=\"$ns\", pod=~\"$pod\"}[1m])))",
     "legendFormat": "{{pod}}.rx",
     "target": "aliasByNode(scale(sumSeriesWithWildcards(sumSeriesWithWildcards(derivative(collectd.$ns.cassandra.$dc.$host.interface.eth0.if_octets.rx), 2), 3), -1), 2, 6)"
    },
    {
     "expr": "0 - sort_desc(sum by (datacenter) (rate(container_network_receive_bytes_total{job=\"kubelet\", namespace=\"$ns\", pod=~\"$pod\"}[1m])))",
     "legendFormat": "{{datacenter}}.rx",
     "target": "aliasByNode(scale(sumSeriesWithWildcards(sumSeriesWithWildcards(derivative(collectd.$ns.cassandra.$dc.$host.interface.eth0.if_octets.rx), 2), 3), -1), 2, 6)"
    },
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_transmit_bytes_total{job=\"kubelet\", namespace=\"$ns\", pod=~\"$pod\"}[1m])))",
     "legendFormat": "{{pod}}.tx",
     "target": "aliasByNode(scale(sumSeriesWithWildcards(sumSeriesWithWildcards(derivative(collectd.$ns.cassandra.$dc.$host.interface.eth0.if_octets.rx), 2), 3), -1), 2, 6)"
    },
    {
     "expr": "sort_desc(sum by (datacenter) (rate(container_network_transmit_bytes_total{job=\"kubelet\", namespace=\"$ns\", pod=~\"$pod\"}[1m])))",
     "legendFormat": "{{datacenter}}.tx",
     "target": "aliasByNode(scale(sumSeriesWithWildcards(sumSeriesWithWildcards(derivative(collectd.$ns.cassandra.$dc.$host.interface.eth0.if_octets.rx), 2), 3), -1), 2, 6)"
    }
   ]
  },
  { "title": "JVM G1 GC Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "JVM G1 Young Generation",
   "type": "graph",
   "description": "Display the amount of time spent with G1 young generation garbage collection times.\n\nThis chart will remain empty if ParNew CMS garbage collection is being used. Ensure that either G1 **or** ParNew CMS is being used homogeneously within a data center for more predictable performance.\n\nTODO: @Alex?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms", "label": "Garbage collection times" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\",datacenter=\"$dc\"}[5m]) / rate(jvm_gc_collection_seconds_count{gc=\"G1 Young Generation\",datacenter=\"$dc\"}[5m])",
     "legendFormat": "{{pod}}",
     "target": "derivative(cassandra.$ns.$dc.$host.jvm.gc.G1-Young-Generation.time)"
    }
   ]
  },
  {
   "title": "JVM G1 Old Generation",
   "type": "graph",
   "description": "Display the amount of time spent with G1 old generation garbage collection times.\n\nThis chart will remain empty if ParNew CMS garbage collection is being used. Ensure that either G1 **or** ParNew CMS is being used homogeneously within a data center for more predictable performance.\n\nTODO: @Alex?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms", "label": "Garbage collection times" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\",datacenter=\"$dc\"}[5m]) / rate(jvm_gc_collection_seconds_count{gc=\"G1 Old Generation\",datacenter=\"$dc\"}[5m])",
     "legendFormat": "{{pod}}",
     "target": "derivative(cassandra.$ns.$dc.$host.jvm.gc.G1-Old-Generation.time)"
    }
   ]
  },
  { "title": "JVM ParNew CMS GC Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } }
 ]
}