{
 "title": "Cassandra TLP - Write Path",
 "tags": [
  "cassandra",
  "tlp"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "env",
    "label": "Namespace",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load, namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load,app_kubernetes_io_name)"
    }
   },
   {
    "name": "dc",
    "label": "Data Center",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load, datacenter)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_Storage_Load, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Write Latencies and Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Write Latency (per table) - p95",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Mean write request latencies of p95"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_WriteLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{table}}.WriteLatency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.WriteLatency.95percentile, 2, 3), 1, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "Write Latency (per host) - p95",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Mean write request latencies of p95"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_WriteLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.WriteLatency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.WriteLatency.95percentile, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "Write Latency (per table and host) - p95",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Write request latencies - p95" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_WriteLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (namespace, datacenter, host, keyspace, table)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{keyspace}}.{{table}}.WriteLatency.p95",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.WriteLatency.95percentile, 2, 3, 9, 10)"
    }
   ]
  },
  {
   "title": "Write Request Counts (per table)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops", "label": "Total write request rate" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_WriteLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"OneMinuteRate\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{table}}.WriteLatency.m1",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.WriteLatency.1MinuteRate, 2, 3), 1, 7, 8, 10)"
    }
   ]
  },
  {
   "title": "Write Request Counts (per host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ops", "label": "Total write request rate" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_WriteLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"OneMinuteRate\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.WriteLatency.m1",
     "target": "aliasByNode(sumSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.WriteLatency.1MinuteRate, 9, 10), 1, 2, 3, 10)"
    }
   ]
  },
  {
   "title": "Write Request Counts (per table and host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "ops", "label": "Write request rate" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_WriteLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"OneMinuteRate\"}) by (namespace, datacenter, host, keyspace, table)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{keyspace}}.{{table}}.WriteLatency.m1",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.WriteLatency.1MinuteRate, 2, 3, 9, 10)"
    }
   ]
  },
  { "title": "CAS Latencies and Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CAS Write Latency (per host) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms", "label": "Mean CAS write latency of p95" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Latency{namespace=\"$env\", datacenter=\"$dc\", scope=\"CASWrite\", unit=\"95thPercentile\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.CASWrite.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.CASWrite.Latency.95percentile, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "CAS Write Timeouts (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    {
     "format": "ops",
     "label": "Mean rate of CAS write timeouts"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Timeouts{namespace=\"$env\", datacenter=\"$dc\", scope=\"CASWrite\", unit=\"OneMinuteRate\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.CASWrite.Timeouts.m1",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.CASWrite.Timeouts.1MinuteRate, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "CAS Write Unavailables (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    {
     "format": "ops",
     "label": "Mean rate of CAS write unavailables"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_Unavailables{namespace=\"$env\", datacenter=\"$dc\", scope=\"CASWrite\", unit=\"OneMinuteRate\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.CASWrite.Unavailables.m1",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.CASWrite.Unavailables.1MinuteRate, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "CAS Write Unfinished Commits (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    {
     "format": "short",
     "label": "Mean unfinished CAS write commits"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_UnfinishedCommit{namespace=\"$env\", datacenter=\"$dc\", scope=\"CASWrite\", unit=\"Count\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.CASWrite.UnfinishedCommit",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.CASWrite.UnfinishedCommit.count, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "CAS Write Conditions Not Met (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    {
     "format": "short",
     "label": "Mean CAS write conditions not met"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_ConditionNotMet{namespace=\"$env\", datacenter=\"$dc\", scope=\"CASWrite\", unit=\"Count\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.CASWrite.ConditionNotMet",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.CASWrite.ConditionNotMet.count, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "CAS Write Contention (per host) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    {
     "format": "short",
     "label": "Mean contended CAS writes of p95"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ClientRequest_ContentionHistogram{namespace=\"$env\", datacenter=\"$dc\", scope=\"CASWrite\", unit=\"95thPercentile\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.CASWrite.Contention.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ClientRequest.CASWrite.ContentionHistogram.95percentile, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  { "title": "CAS Stage Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CAS Prepare Latency (per table) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Mean CAS prepare latencies of p95"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_CasPrepareLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{table}}.CASPrepare.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.CasPrepareLatency.95percentile, 2, 3), 1, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "CAS Prepare Latency (per host) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Mean CAS prepare latencies of p95"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_CasPrepareLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.CASPrepare.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.CasPrepareLatency.95percentile, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "CAS Prepare Latency (per table and host) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "ms", "label": "CAS prepare latencies - p95" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_CasPrepareLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (namespace, datacenter, host, keyspace, table)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{keyspace}}.{{table}}.CASPrepare.Latency.p95",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.CasPrepareLatency.95percentile, 2, 3, 9, 10)"
    }
   ]
  },
  {
   "title": "CAS Propose Latency (per table) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Mean CAS propose latencies of p95"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_CasProposeLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{table}}.CASPropose.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.CasProposeLatency.95percentile, 2, 3), 1, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "CAS Propose Latency (per host) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Mean CAS propose latencies of p95"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_CasProposeLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.CASPropose.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.CasProposeLatency.95percentile, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "CAS Propose Latency (per table and host) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "ms", "label": "CAS propose latencies - p95" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_CasProposeLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (namespace, datacenter, host, keyspace, table)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{keyspace}}.{{table}}.CASPropose.Latency.p95",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.CasProposeLatency.95percentile, 2, 3, 9, 10)"
    }
   ]
  },
  {
   "title": "CAS Commit Latency (per table) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Mean CAS commit latencies of p95"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_CasCommitLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{table}}.CASCommit.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.CasCommitLatency.95percentile, 2, 3), 1, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "CAS Commit Latency (per host) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Mean CAS commit latencies of p95"
    }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_CasCommitLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.CASCommit.Latency.p95",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.CasCommitLatency.95percentile, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "CAS Commit Latency (per table and host) - p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "ms", "label": "CAS commit latencies - p95" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_CasCommitLatency{namespace=\"$env\", datacenter=\"$dc\", unit=\"95thPercentile\"}) by (namespace, datacenter, host, keyspace, table)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{keyspace}}.{{table}}.CASCommit.Latency.p95",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.CasCommitLatency.95percentile, 2, 3, 9, 10)"
    }
   ]
  },
  { "title": "Memtables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Memtable Column Count (per table)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Mean memtable column count" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableColumnsCount{namespace=\"$env\", datacenter=\"$dc\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{table}}.MemtableColumnsCount",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableColumnsCount.value, 2, 3), 1, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "Memtable Column Count (per host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Mean memtable column count" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableColumnsCount{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.MemtableColumnsCount",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableColumnsCount.value, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "Memtable Column Count (per table and host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Memtable column count" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableColumnsCount{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host, keyspace, table)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{keyspace}}.{{table}}.MemtableColumnsCount",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableColumnsCount.value, 2, 3, 9, 10)"
    }
   ]
  },
  {
   "title": "Memtable Live Data Size (per table)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes", "label": "Mean memtable live data size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableLiveDataSize{namespace=\"$env\", datacenter=\"$dc\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{table}}.MemtableLiveDataSize",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableLiveDataSize.value, 2, 3), 1, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "Memtable Live Data Size (per host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "bytes", "label": "Mean memtable live data size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableLiveDataSize{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.MemtableLiveDataSize",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableLiveDataSize.value, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "Memtable Live Data Size (per table and host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "bytes", "label": "Memtable live data size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableLiveDataSize{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host, keyspace, table)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{keyspace}}.{{table}}.MemtableLiveDataSize",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableLiveDataSize.value, 2, 3, 9, 10)"
    }
   ]
  },
  {
   "title": "Memtable On-Heap Size (per table)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes", "label": "Mean memtable on-heap size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableOnHeapSize{namespace=\"$env\", datacenter=\"$dc\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{table}}.MemtableOnHeapSize",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableOnHeapSize.value, 2, 3), 1, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "Memtable On-Heap Size (per host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "bytes", "label": "Mean memtable on-heap size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableOnHeapSize{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.MemtableOnHeapSize",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableOnHeapSize.value, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "Memtable On-Heap Size (per table and host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "bytes", "label": "Memtable on-heap size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableOnHeapSize{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host, keyspace, table)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{keyspace}}.{{table}}.MemtableOnHeapSize",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableOnHeapSize.value, 2, 3, 9, 10)"
    }
   ]
  },
  {
   "title": "Memtable Off-Heap Size (per table)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bytes", "label": "Mean memtable off-heap size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableOffHeapSize{namespace=\"$env\", datacenter=\"$dc\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{table}}.MemtableOffHeapSize",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableOffHeapSize.value, 2, 3), 1, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "Memtable Off-Heap Size (per host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "bytes", "label": "Mean memtable off-heap size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableOffHeapSize{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.MemtableOffHeapSize",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableOffHeapSize.value, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "Memtable Off-Heap Size (per table and host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "bytes", "label": "Memtable off-heap size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_MemtableOffHeapSize{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host, keyspace, table)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{keyspace}}.{{table}}.MemtableOffHeapSize",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.MemtableOffHeapSize.value, 2, 3, 9, 10)"
    }
   ]
  },
  {
   "title": "Memtable Total Heap Size (per table)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "bytes", "label": "Mean memtable total heap size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_AllMemtablesHeapSize{namespace=\"$env\", datacenter=\"$dc\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{table}}.AllMemtablesHeapSize",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.AllMemtablesHeapSize.value, 2, 3), 1, 7, 8, 9)"
    }
   ]
  },
  {
   "title": "Memtable Total Heap Size (per host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "bytes", "label": "Mean memtable total heap size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_AllMemtablesHeapSize{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.AllMemtablesHeapSize",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.AllMemtablesHeapSize.value, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "Memtable Total Heap Size (per table and host)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "bytes", "label": "Memtable total heap size" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Table_AllMemtablesHeapSize{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host, keyspace, table)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{keyspace}}.{{table}}.AllMemtablesHeapSize",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ColumnFamily.$ks.$table.AllMemtablesHeapSize.value, 2, 3, 9, 10)"
    }
   ]
  },
  { "title": "Mutations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Pending Mutations (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short", "label": "Mean pending mutations" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ThreadPools{namespace=\"$env\", datacenter=\"$dc\", status_pool=\"PendingTasks\", thread_type=\"request\", thread_pool=\"MutationStage\"}) by (namespace, datacenter, host, thread_pool, status_pool)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.request.MutationStage.PendingTasks.value, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "Active Mutations (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short", "label": "Mean active mutations" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ThreadPools{namespace=\"$env\", datacenter=\"$dc\", status_pool=\"ActiveTasks\", thread_type=\"request\", thread_pool=\"MutationStage\"}) by (namespace, datacenter, host, thread_pool, status_pool)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.request.MutationStage.ActiveTasks.value, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  { "title": "Dropped Mutations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Dropped Mutations (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "ops", "label": "Mean dropped mutation rate" }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_DroppedMessages_Dropped{namespace=\"$env\", datacenter=\"$dc\", message_type=\"MUTATION\", unit=\"OneMinuteRate\"}) by (namespace, datacenter, host, message_type)",
     "legendFormat": "{{keyspace}}.{{table}}.DroppedMessages.{{message_type}}.m1",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.DroppedMessage.MUTATION.Dropped.1MinuteRate, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "Dropped Counter Mutations (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    {
     "format": "ops",
     "label": "Mean dropped counter mutation rate"
    }
   ],
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_DroppedMessages_Dropped{namespace=\"$env\", datacenter=\"$dc\", message_type=\"COUNTER_MUTATION\", unit=\"OneMinuteRate\"}) by (namespace, datacenter, host, message_type)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.DroppedMessages.{{message_type}}.m1",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.DroppedMessage.COUNTER_MUTATION.Dropped.1MinuteRate, 9, 10), 1, 2, 3, 9)"
    }
   ]
  },
  { "title": "Commit Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Commit Log Sizes (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bytes", "label": "Mean commit log sizes" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_CommitLog_TotalCommitLogSize{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.TotalCommitLogSize",
     "target": "aliasSub(aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.CommitLog.TotalCommitLogSize.value, 9, 10), 1, 2, 3), '(.*)', '\\1.TotalCommitLogSize')"
    }
   ]
  },
  {
   "title": "Disk Load (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "bytes", "label": "Disk load" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_Storage_Load{namespace=\"$env\", datacenter=\"$dc\"}) by (namespace, datacenter, host)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.Storage.Load",
     "target": "aliasByNode(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.Storage.Load.count, 3, 9)"
    }
   ]
  },
  {
   "title": "Pending Commit Log Tasks (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "Mean pending commit log tasks" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ThreadPools{namespace=\"$env\", datacenter=\"$dc\", status_pool=\"PendingTasks\", thread_type=\"internal\", thread_pool=\"MemtableFlushWriter\"}) by (namespace, datacenter, host, status_pool, thread_pool)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.internal.MemtableFlushWriter.PendingTasks.value, 9), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "Active Commit Log Tasks (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "Mean active commit log tasks" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ThreadPools{namespace=\"$env\", datacenter=\"$dc\", status_pool=\"ActiveTasks\", thread_type=\"internal\", thread_pool=\"MemtableFlushWriter\"}) by (namespace, datacenter, host, status_pool, thread_pool)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.internal.MemtableFlushWriter.ActiveTasks.value, 9), 1, 2, 3, 9)"
    }
   ]
  },
  {
   "title": "Blocked Commit Log Tasks (per host)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "Mean blocked commit log tasks" }
   ],
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_ThreadPools{namespace=\"$env\", datacenter=\"$dc\", status_pool=\"CurrentlyBlockedTasks\", thread_type=\"internal\", thread_pool=\"MemtableFlushWriter\"}) by (namespace, datacenter, host, status_pool, thread_pool)",
     "legendFormat": "{{namespace}}.{{datacenter}}.{{host}}.{{thread_pool}}.{{status_pool}}",
     "target": "aliasByNode(averageSeriesWithWildcards(cassandra.$env.$dc.$host.org.apache.cassandra.metrics.ThreadPools.internal.MemtableFlushWriter.CurrentlyBlockedTasks.count, 9), 1, 2, 3, 9)"
    }
   ]
  }
 ]
}