apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
  - image: "us.icr.io/cassandra-operator/cassandra-operator"
    context: .
    docker:
      dockerfile: Dockerfile

  - image: "us.icr.io/cassandra-operator/prober"
    context: prober/
    docker:
      dockerfile: Dockerfile

  - image: "us.icr.io/cassandra-operator/cassandra"
    context: cassandra/
    docker:
      dockerfile: Dockerfile

  - image: "us.icr.io/cassandra-operator/jolokia"
    context: jolokia/
    docker:
      dockerfile: Dockerfile

  tagPolicy:
    envTemplate:
      template: "{{.USER}}"
  local:
    push: true
    concurrency: 1
deploy:
  helm:
    releases:
    - name: "cassandra-operator-{{.USER}}"
      chartPath: ./cassandra-operator
      valuesFiles:
      - cassandra-operator/values.yaml
      setValueTemplates:
        container.image: "us.icr.io/cassandra-operator/cassandra-operator:{{.USER}}"
        container.imagePullSecret: icm-coreeng-pull-secret
        container.imagePullPolicy: Always
        logLevel: debug
        proberImage: "us.icr.io/cassandra-operator/prober:{{.USER}}"
        jolokiaImage: "us.icr.io/cassandra-operator/jolokia:{{.USER}}"
        cassandraImage: "us.icr.io/cassandra-operator/cassandra:{{.USER}}"
      createNamespace: true
      wait: true
      packaged:
        version: "0.0.0-{{.USER}}"
        appVersion: "0.0.0-{{.USER}}"
      # Sets image.tag and image.repository separately
      recreatePods: true
#  kubectl:
#    manifests:
#    - ./config/samples/tls-single-cluster.yaml
profiles:
- name: kind
  activation:
  - kubeContext: kind-cassandra
  build:
    local:
      push: false # if `false` images will be loaded into local kind cluster nodes
# Figure out to pull in kind cluster from local nodes a d not from ICR
  deploy:
    helm:
      releases:
      - name: "cassandra-operator-{{.USER}}"
        chartPath: ./cassandra-operator
        valuesFiles:
        - cassandra-operator/values.yaml
        setValueTemplates:
          container.image: "us.icr.io/cassandra-operator/cassandra-operator:{{.USER}}"
          container.imagePullSecret: icm-coreeng-pull-secret
          container.imagePullPolicy: IfNotPresent
          logLevel: debug
          proberImage: "us.icr.io/cassandra-operator/prober:{{.USER}}"
          jolokiaImage: "us.icr.io/cassandra-operator/jolokia:{{.USER}}"
          cassandraImage: "us.icr.io/cassandra-operator/cassandra:{{.USER}}"
        createNamespace: true
        wait: true
        packaged:
          version: "0.0.0-{{.USER}}"
          appVersion: "0.0.0-{{.USER}}"
        # Sets image.tag and image.repository separately
        recreatePods: true
