apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
  - image: "us.icr.io/cassandra-operator/cassandra-operator"
    context: .
    docker:
      dockerfile: Dockerfile
  - image: "us.icr.io/cassandra-operator/prober"
    context: prober/
    docker:
      dockerfile: Dockerfile
  - image: "us.icr.io/cassandra-operator/cassandra"
    context: cassandra/
    docker:
      dockerfile: Dockerfile
  - image: "us.icr.io/cassandra-operator/jolokia"
    context: jolokia/
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    envTemplate:
      template: "{{.USER}}"
  local:
    push: true
    concurrency: 4
#    useDockerCLI: true
#build:
#  artifacts:
#  - image: "738806440043.dkr.ecr.us-east-1.amazonaws.com/cassandra-operator"
#    context: .
#    docker:
#      dockerfile: Dockerfile
#  - image: "738806440043.dkr.ecr.us-east-1.amazonaws.com/prober"
#    context: prober/
#    docker:
#      dockerfile: Dockerfile
#  - image: "738806440043.dkr.ecr.us-east-1.amazonaws.com/cassandra"
#    context: cassandra/
#    docker:
#      dockerfile: Dockerfile
#  - image: "738806440043.dkr.ecr.us-east-1.amazonaws.com/jolokia"
#    context: jolokia/
#    docker:
#      dockerfile: Dockerfile
#  tagPolicy:
#    envTemplate:
#      template: "{{.USER}}"
#  local:
#    push: true
#    concurrency: 4
deploy:
  helm:
    releases:
    - name: "cassandra-operator-{{.USER}}"
      chartPath: ./cassandra-operator
      valuesFiles:
      - cassandra-operator/values.yaml
      setValueTemplates:
        container.image: "us.icr.io/cassandra-operator/cassandra-operator:{{.USER}}"
        container.imagePullSecret: icm-coreeng-pull-secret
        container.imagePullPolicy: Always
        logLevel: debug
        proberImage: "us.icr.io/cassandra-operator/prober:{{.USER}}"
        jolokiaImage: "us.icr.io/cassandra-operator/jolokia:{{.USER}}"
        cassandraImage: "us.icr.io/cassandra-operator/cassandra:{{.USER}}"
        admissionWebhooks.enabled: true
        clusterDashboards.enabled[0]: "datastax"
        clusterDashboards.enabled[1]: "instaclustr"
        clusterDashboards.enabled[2]: "prober"
        clusterDashboards.enabled[3]: "reaper"
        clusterDashboards.enabled[4]: "tlp"
        monitoring.enabled: true
        monitoring.grafanaDashboard.enabled: true
        monitoring.grafanaDashboard.datasourceName: "Prometheus"
        monitoring.serviceMonitor.enabled: true
        monitoring.serviceMonitor.scrapeInterval: 30s
      createNamespace: true
      wait: true
      recreatePods: true
      packaged:
        version: "0.0.0-{{.USER}}"
        appVersion: "0.0.0-{{.USER}}"
#  kubectl:
#    manifests:
#    - ./config/samples/cassandracluster_local.yaml
profiles:
- name: kind
  activation:
  - kubeContext: kind-cassandra
  build:
    local:
      # when `push` set to `false` the images are not pushed to ICR but loaded into kind cluster nodes
      push: false
  deploy:
    helm:
      releases:
      - name: "cassandra-operator-{{.USER}}"
        chartPath: ./cassandra-operator
        valuesFiles:
        - cassandra-operator/values.yaml
        setValueTemplates:
          container.image: "us.icr.io/cassandra-operator/cassandra-operator:{{.USER}}"
          container.imagePullPolicy: Never
          logLevel: debug
          proberImage: "us.icr.io/cassandra-operator/prober:{{.USER}}"
          jolokiaImage: "us.icr.io/cassandra-operator/jolokia:{{.USER}}"
          cassandraImage: "us.icr.io/cassandra-operator/cassandra:{{.USER}}"
        createNamespace: true
        wait: true
        packaged:
          version: "0.0.0-{{.USER}}"
          appVersion: "0.0.0-{{.USER}}"
