apiVersion: db.ibm.com/v1alpha1
kind: CassandraCluster
metadata:
  name: test-cluster
spec:
  imagePullSecretName: icm-coreeng-pull-secret
  adminRoleSecretName: admin-role
  cassandra:
    imagePullPolicy: IfNotPresent
    numSeeds: 2
    logLevel: debug
    purgeGossip: false
    persistence:
      enabled: false
      commitLogVolume: false
      dataVolumeClaimSpec:
        resources:
          requests:
            storage: 20Gi
      commitLogVolumeClaimSpec:
        resources:
          requests:
            storage: 20Gi
    zonesAsRacks: false
    resources:
      limits:
        cpu: "1"
        memory: 1.5Gi
      requests:
        memory: 1.5Gi
        cpu: "1"
  jvm:
    maxHeapSize: 1024M
  cqlConfigMapLabelKey: cql-scripts
  dcs:
  - name: dc1
    replicas: 3
  - name: dc2
    replicas: 3
  ingress:
    domain: icm-cassandra-dev-3f3037ed650e84f558a8839c9ec8a6ed-0000.us-south.containers.appdomain.cloud
    secret: icm-cassandra-dev-3f3037ed650e84f558a8839c9ec8a6ed-0000
    annotations:
      "ingress.bluemix.net/redirect-to-https": "True"
  prober:
    logLevel: debug
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
    jolokia:
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
  reaper:
    incrementalRepair: false
    repairParallelism: "DATACENTER_AWARE"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 512Mi
        cpu: "0.5"
      limits:
        memory: 512Mi
        cpu: "0.5"
    tolerations: []
    nodeSelector: {}
    repairIntensity: "1.0"
    keyspace: reaper
    repairSchedules:
      enabled: false
      repairs:
      - keyspace: system_traces
        tables: [events]
        scheduleDaysBetween: 7
        scheduleTriggerTime: "2020-11-15T14:00:00"
        datacenters: [dc1]
        repairThreadCount: 2
        intensity: "1.0"
        incrementalRepair: false
        repairParallelism: "DATACENTER_AWARE"
    serviceMonitor:
      enabled: false
      namespace: ""
      labels: {}
      scrapeInterval: 60s
  systemKeyspaces:
    dcs:
    - name: dc1
      rf: 2
    - name: dc2
      rf: 2
    names:
    - system_distributed
    - system_traces
  hostPort:
    enabled: false
    useExternalHostIP: false # If set to false host internal ip will be used
    ports:
    - intra
    - cql
    - jmx
    - thrift
  monitoring:
    enabled: false
    agent: "tlp"
    serviceMonitor:
      enabled: false
      namespace: ""
      labels: {}
      scrapeInterval: 30s
  jmx: {}
  encryption:
    server:
      internodeEncryption: none # If set to `all` all internode traffic are encrypted
      tlsSecret:
        name: cassandra-cluster-tls
    client:
      enabled: false
      tlsSecret:
        name: cassandra-client-tls
      requireClientAuth: false
