apiVersion: db.ibm.com/v1alpha1
kind: CassandraCluster
metadata:
  name: test-cluster
spec:
  cassandra:
    image: ""
    imagePullPolicy: IfNotPresent
    numSeeds: 2
    persistence:
      enabled: false
      commitLogVolume: false
      dataVolumeClaimSpec:
        resources:
          requests:
            storage: 20Gi
      commitLogVolumeClaimSpec:
        resources:
          requests:
            storage: 20Gi
    zonesAsRacks: false
    resources:
      requests:
        memory: 1.5Gi
        cpu: "1"
  cqlConfigMapLabelKey: cql-scripts
  dcs:
  - name: dc1
    replicas: 3
  - name: dc2
    replicas: 3
  imagePullSecretName: all-icr-io
  prober:
    debug: true
    image: ""
    imagePullPolicy: IfNotPresent
    jolokia:
      image: ""
      imagePullPolicy: IfNotPresent
    ingress:
      domain: "v4-us-south-3f3037ed650e84f558a8839c9ec8a6ed-0000.us-south.containers.appdomain.cloud"
      secret: "v4-us-south-3f3037ed650e84f558a8839c9ec8a6ed-0000"
      annotations:
        "ingress.bluemix.net/redirect-to-https": "True"
  reaper:
    image: ""
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 512Mi
        cpu: "0.5"
      limits:
        memory: 512Mi
        cpu: "0.5"
    tolerations: []
    nodeSelector: {}
    repairIntensity: "1.0"
    datacenterAvailability: each
    keyspace: reaper_db
    dcs:
    - name: dc1
      replicas: 2
    - name: dc2
      replicas: 2
    scheduleRepairs:
      enabled: true
      repairs:
      - keyspace: system_traces
        tables: [events]
        scheduleDaysBetween: 7
        scheduleTriggerTime: "2020-11-15T14:00:00"
        datacenters: [dc1]
        repairThreadCount: 2
        intensity: "1.0"
        incrementalRepair: false
        repairParallelism: "datacenter_aware"
  systemKeyspaces:
    dcs:
    - name: dc1
      rf: 2
    - name: dc2
      rf: 2
    names:
    - system_distributed
    - system_traces
  hostPort:
    enabled: true
    useExternalHostIP: false # If set to false host internal ip will be used
    ports:
    - intra
    - cql
    - jmx
    - thrift
