{
 "title": "Cassandra - Reaper2",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(io_cassandrareaper_jmx_JmxConnectionFactory_jmxConnectionsIntializer_count,instance)"
   },
   {
    "name": "job",
    "query": "label_values(Cassandra_RepairRunner_segmentsTotal,job_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Job Progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "RepairRunner_repairProgress{instance=\"$instance\",job_id=\"$job\"}",
     "legendFormat": "job id: {{job_id}}"
    }
   ]
  },
  {
   "title": "Last job duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(Cassandra_RepairRunner_millisSinceLastRepair{instance=\"$instance\",job_id=\"$job\"}[1m])",
     "legendFormat": "job id: {{job_id}}"
    }
   ]
  },
  {
   "title": "Ignored segments ",
   "type": "graph",
   "description": "That graph shows amount of ignored by different reasons segment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_ignores{instance=\"$instance\"}[1m])",
     "legendFormat": "Total ignored"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_ignores_on_client_timeout{instance=\"$instance\"}[1m])",
     "legendFormat": "ignored on client timeout"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_ignores_on_connection_error{instance=\"$instance\"}[1m])",
     "legendFormat": "ignored on connection errors"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_ignores_on_read_timeout{instance=\"$instance\"}[1m])",
     "legendFormat": "ignored on read timeout"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_ignores_on_write_timeout{instance=\"$instance\"}[1m])",
     "legendFormat": "ignored on write timeout"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_ignores_on_unavailable{instance=\"$instance\"}[1m])",
     "legendFormat": "ignored on Cassandra unavailable"
    }
   ]
  },
  {
   "title": "Segments retries amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_retries{instance=\"$instance\"}[1m])",
     "legendFormat": "Total retries"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_retries_on_client_timeout{instance=\"$instance\"}[1m])",
     "legendFormat": "retries on timeout"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_retries_on_connection_erroror{instance=\"$instance\"}[1m])",
     "legendFormat": "retries on connection errors"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_retries_on_read_timeout{instance=\"$instance\"}[1m])",
     "legendFormat": "retries on read timeout"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_retries_on_write_timeout{instance=\"$instance\"}[1m])",
     "legendFormat": "retries on write timeout"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_retries_on_unavailable{instance=\"$instance\"}[1m])",
     "legendFormat": "retries on Cassandra unavailable"
    }
   ]
  },
  {
   "title": "Lead operations",
   "type": "graph",
   "description": "Shows Cassandra coordinator releasing operations for segment processing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(io_cassandrareaper_service_SegmentRunner_releaseLead_count{instance=\"$instance\"}[1m])",
     "legendFormat": "Release lead: {{instance}}"
    },
    {
     "expr": "increase(io_cassandrareaper_service_SegmentRunner_takeLead_count{instance=\"$instance\"}[1m])",
     "legendFormat": "Take lead: {{instance}}"
    },
    {
     "expr": "increase(io_cassandrareaper_service_SegmentRunner_takeLead_failed{instance=\"$instance\"}[1m])",
     "legendFormat": "Take lead failed: {{instance}}"
    },
    {
     "expr": "increase(io_cassandrareaper_service_SegmentRunner_renewLead_failed{instance=\"$instance\"}[1m])",
     "legendFormat": "Renew lead failed: {{instance}}"
    }
   ]
  },
  {
   "title": "R/W timeouts",
   "type": "graph",
   "description": "Timeouts on read/write operations in Cassandra cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_read_timeouts{instance=\"$instance\"}[1m])",
     "legendFormat": "read timeout"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_write_timeouts{instance=\"$instance\"}[1m])",
     "legendFormat": "write timeout"
    }
   ]
  },
  {
   "title": "Cassandra cluster errors",
   "type": "graph",
   "description": "Different type of errors on cooperation reaper with Cassandra cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_unavailables{instance=\"$instance\"}[1m])",
     "legendFormat": "Cluster unavailable"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_connection_errors{instance=\"$instance\"}[1m])",
     "legendFormat": "Connection errors"
    },
    {
     "expr": "increase(com_datastax_driver_core_Cluster_cassandra_connection_errors{instance=\"$instance\"}[1m])",
     "legendFormat": "Authentication errors:"
    }
   ]
  },
  {
   "title": "Cassandra cluster pod connections",
   "type": "graph",
   "description": "This graph shows connection to Cassandra cluster pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Cassandra_JmxConnectionFactory{instance=\"$instance\"}[1h])",
     "legendFormat": "Cassandra instance: {{cassandra_ip}}"
    }
   ]
  },
  {
   "title": "Number of JMX Connections to Cassandra",
   "type": "graph",
   "description": "Number of JMX Connections to Cassandra",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "io_cassandrareaper_jmx_JmxConnectionFactory_jmxConnectionsIntializer_count{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Opened Files",
   "type": "graph",
   "description": "Amount of opened files. Reaper takes snapshots of current segments. Write logs to files and store some information about run_history. Looks like they are faced with too many opened file descriptors issue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(io_cassandrareaper_service_SegmentRunner_openFiles_count{instance=\"$instance\"}[5m])",
     "legendFormat": "instance: {{instance}}"
    }
   ]
  }
 ]
}