replicas: 1
container:
  image: us.icr.io/cassandra-operator/cassandra-operator:0.2.0
  # imagePullSecret: container-registry-secret
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 500m
      memory: 200Mi
logLevel: info
logFormat: json
proberImage: us.icr.io/cassandra-operator/prober:0.2.0 # this value will be updated on next release in GHA
jolokiaImage: us.icr.io/cassandra-operator/jolokia:0.2.0 # this value will be updated on next release in GHA
cassandraImage: us.icr.io/cassandra-operator/cassandra:3.11.9-0.2.0 # this value will be updated on next release in GHA
reaperImage: thelastpickle/cassandra-reaper:2.3.1
clusterDashboards:
  enabled: []
  namespace: ""
  labels:
    grafana_dashboard: "1"
monitoring:
  enabled: false
  grafanaDashboard:
    enabled: false
    namespace: ""
    labels:
      grafana_dashboard: "1"
    datasourceName: ""
  serviceMonitor:
    enabled: false
    namespace: ""
    labels:
      operator: cassandra-operator
    scrapeInterval: 30s
admissionWebhooks:
  enabled: true
