replicas: 1
container:
  image: us.icr.io/cassandra-operator/cassandra-operator:0.1.0
  # imagePullSecret: container-registry-secret
  imagePullPolicy: Always
  restartPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 500m
      memory: 200Mi
logLevel: info
logFormat: json
proberImage: us.icr.io/cassandra-operator/prober:0.1.0 # this value will be updated on next release in GHA
jolokiaImage: us.icr.io/cassandra-operator/jolokia:0.1.0 # this value will be updated on next release in GHA
cassandraImage: us.icr.io/cassandra-operator/cassandra:3.11.9-0.1.0 # this value will be updated on next release in GHA
reaperImage: thelastpickle/cassandra-reaper:2.3.1
clusterDashboards:
  enabled: []
  namespace: ""
  labels:
    grafana_dashboard: "1"
admissionWebhooks:
  enabled: true