{
 "title": "Cassandra - Prober",
 "tags": [
  "cassandra",
  "prober"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kube_pod_container_info{container=\"prober\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Requests by Route",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{namespace=\"$namespace\", pod=\"$instance\", path!~\"/healthz/.*|/ping\", status=\"success\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Number of Healthz Requests",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{namespace=\"$namespace\", pod=\"$instance\", path=~\"/healthz/.*\", status=\"success\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_requests_total{namespace=\"$namespace\", pod=\"$instance\", status=\"success\"}[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_requests_total{namespace=\"$namespace\", pod=\"$instance\", status=\"fail\"}[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_response_time_milliseconds{quantile=\"0.99\", namespace=\"$namespace\", pod=\"$instance\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "P90 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_response_time_milliseconds{quantile=\"0.9\", namespace=\"$namespace\", pod=\"$instance\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "P50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_response_time_milliseconds{quantile=\"0.5\", namespace=\"$namespace\", pod=\"$instance\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$instance\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$instance\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}