{
 "title": "Cassandra Datastax - Cluster Condensed",
 "description": "Single pane of glass for most important Cassandra metrics",
 "tags": [
  "cassandra",
  "datastax"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "rack",
    "label": "Rack",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{cluster=~\"$cluster\", dc=~\"$dc\"}, rack)"
    }
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(mcac_table_read_latency_total{cluster=~\"$cluster\", dc=~\"$dc\"}, keyspace)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(mcac_table_read_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", keyspace=~\"$keyspace\"}, table)"
    }
   },
   { "name": "by", "label": "Group By", "query": "cluster,dc,rack,instance" },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{}, cluster)"
    }
   },
   {
    "name": "dc",
    "label": "DataCenter",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{cluster=~\"$cluster\"}, dc)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}, instance)"
    }
   },
   {
    "name": "latency",
    "label": "Percentile",
    "query": "0.999,0.99,0.98,0.95,0.90,0.75,0.50"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Up",
   "type": "stat",
   "description": "Nodes that are currently running in this time window",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(mcac_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"} >= 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "stat",
   "description": "Nodes that are currently not running in this time window",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(absent(sum(rate(mcac_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[5m])))) OR vector(0)"
    }
   ]
  },
  {
   "title": "Compactions / $rate",
   "type": "stat",
   "description": "Rate of compactions during this window",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mcac_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "CQL Requests / $rate",
   "type": "stat",
   "description": "Rate of CQL requests during this window",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dse_client_request_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Dropped Messages / $rate",
   "type": "stat",
   "description": "Rate of Dropped requests during this window",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(mcac_table_dropped_mutations_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "options": {
    "content": "<a href=\"https://cassandra.apache.org\" target=\"new\"><img src=\"https://cassandra.apache.org/assets/img/logo-white.svg\"/></a>"
   }
  },
  {
   "title": "CQL Clients",
   "type": "stat",
   "description": "Number of connected clients during this time window",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mcac_client_connected_native_clients{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Timeouts / $rate",
   "type": "stat",
   "description": "Client timeouts over the last $rate",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(mcac_client_request_timeouts_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Hints / $rate",
   "type": "stat",
   "description": "Hints stored over the last $rate",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(mcac_storage_hints_on_disk_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "stat",
   "description": "Data",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mcac_table_live_disk_space_used_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "GC Time / $rate",
   "type": "stat",
   "description": "Data",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mcac_jvm_gc_time{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate]))"
    }
   ]
  },
  { "title": "Condensed Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests Served / $by / $rate",
   "type": "graph",
   "description": "(no keyspace/table filters apply)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mcac_client_request_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate])) by ($by, request_type)",
     "legendFormat": "{{$by}}:{{request_type}}"
    },
    {
     "expr": "sum(mcac_client_connected_native_clients{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}}:Clients Connected"
    }
   ]
  },
  {
   "title": "Coordinator $latency Latency / $by",
   "type": "graph",
   "description": "(no keyspace/table filters apply)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($latency, sum(rate(mcac_client_request_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate])) by (le, request_type, $by))",
     "legendFormat": "$by:{{$by}} {{$latency}} {{request_type}}"
    }
   ]
  },
  {
   "title": "Memtable Space $keyspace.$table / $by",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(mcac_table_memtable_off_heap_size{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}} : Off Heap"
    },
    {
     "expr": "sum(mcac_table_memtable_on_heap_size{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}} : On Heap"
    },
    {
     "expr": "sum(idelta(mcac_table_memtable_switch_count_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}} : Flushes"
    },
    {
     "expr": "sum(idelta(mcac_table_pending_flushes_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}} : Pending Flushes"
    }
   ]
  },
  {
   "title": "Compactions $keyspace.$table / $by",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mcac_table_compaction_bytes_written_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{by}} : Bytes Compacted"
    },
    {
     "expr": "sum(irate(mcac_table_pending_compactions{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{by}} : Pending Compactions"
    },
    {
     "expr": "sum(irate(mcac_compaction_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{by}} : Completed Compactions"
    }
   ]
  },
  {
   "title": "Table $latency Latency / $by",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($latency, sum(irate(mcac_table_range_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Range Scan"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(mcac_table_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Read"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(mcac_table_write_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Write"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(mcac_table_coordinator_read_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Coordinator Read"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(mcac_table_coordinator_scan_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", instance=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Coordinator Range Scan"
    }
   ]
  },
  {
   "title": "Streaming / $by / $rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mcac_streaming_total_incoming_bytes_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}: Incoming Stream"
    },
    {
     "expr": "sum(irate(mcac_streaming_total_outgoing_bytes_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}: Outgoing Stream"
    }
   ]
  }
 ]
}