{
 "title": "Cassandra Datastax - System & Node Metrics",
 "description": "Operating System Metrics and Apache Cassandra Node Information",
 "tags": [
  "cassandra",
  "datastax"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": {
    "content": "<a href=\"https://cassandra.apache.org\" target=\"new\"><img src=\"https://cassandra.apache.org/assets/img/logo-white.svg\"/></a>"
   }
  },
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - ((sum(irate(collectd_cpu_total{instance='$host', type='idle'}[$rate])) by (instance) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) by (instance)))) * 100"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "description": "Percentage of memory used (ignoring page cache)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * ((sum(collectd_memory{instance=\"$host\", memory=\"free\"}) + sum(collectd_memory{instance=\"$host\", memory=\"cached\"}) + sum(collectd_memory{instance=\"$host\", memory=\"buffered\"})) / sum(collectd_memory{instance=\"$host\"}))"
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "gauge",
   "description": "Percentage of swap in use",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(collectd_swap{instance='$host',swap='used'}) / sum(collectd_swap{instance='$host'})) * 100"
    }
   ]
  },
  {
   "title": "Root Disk Used",
   "type": "gauge",
   "description": "Percentage of root disk in use",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(collectd_df_df_complex{instance=\"$host\", df=\"root\", type=\"used\"}) / sum(collectd_df_df_complex{instance=\"$host\", df=\"root\"})) * 100"
    }
   ]
  },
  {
   "title": "Data Disk Used",
   "type": "gauge",
   "description": "Percentage of data disk in use",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(collectd_df_df_complex{instance=\"$host\", df=\"var-lib-cassandra\", type=\"used\"}) / sum(collectd_df_df_complex{instance=\"$host\", df=\"var-lib-cassandra\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(collectd_load_shortterm{instance=\"$host\"}) / count(count(collectd_cpu_total{instance=\"$host\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(collectd_load_midterm{instance=\"$host\"}) / count(count(collectd_cpu_total{instance=\"$host\"}) by (cpu)) * 100"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(collectd_cpu_total{instance=\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total amount of system memory",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(collectd_memory{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Total Swap",
   "type": "stat",
   "description": "Total amount of swap space",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(collectd_swap{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Total Root Disk",
   "type": "stat",
   "description": "Total amount of disk space",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(collectd_df_df_complex{df=\"root\",instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Total Data Disk",
   "type": "stat",
   "description": "Total amount of disk space",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(collectd_df_df_complex{df=\"var-lib-cassandra\",instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "stat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "collectd_load_shortterm{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "description": "Uptime of the host",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "collectd_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(collectd_cpu_total{instance='$host',type='system'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum(irate(collectd_cpu_total{instance='$host',type='user'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum(irate(collectd_cpu_total{instance='$host',type='wait'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
       "legendFormat": "Busy IOWait"
      },
      {
       "expr": "sum(irate(collectd_cpu_total{instance='$host',type='softirq'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
       "legendFormat": "Busy IRQ"
      },
      {
       "expr": "sum(irate(collectd_cpu_total{instance='$host',type!='idle',type!='system',type!='user',type!='wait',type!='softirq'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum(irate(collectd_cpu_total{instance='$host',type='idle'}[$rate])) / sum(irate(collectd_cpu_total{instance='$host'}[$rate])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Basic memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(collectd_memory{instance=\"$host\"})",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "sum(collectd_memory{instance=\"$host\"}) - sum(collectd_memory{instance=\"$host\", memory=\"free\"}) - sum(collectd_memory{instance=\"$host\", memory=\"cached\"}) - sum(collectd_memory{instance=\"$host\", memory=\"buffered\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "sum(collectd_memory{instance=\"$host\", memory=\"cached\"}) + sum(collectd_memory{instance=\"$host\", memory=\"buffered\"})",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "sum(collectd_memory{instance=\"$host\", memory=\"free\"})",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "sum(collectd_swap{instance=\"$host\"}) - sum(collectd_swap{instance=\"$host\", swap=\"free\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic Network / Disk Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic / Second",
     "type": "graph",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bps", "label": "Receive (-) /  Send (+)" }
     ],
     "targets": [
      {
       "expr": "irate(collectd_interface_if_octets_rx_total{instance='$host'}[$rate]) * 8",
       "legendFormat": "{{interface}} receive"
      },
      {
       "expr": "irate(collectd_interface_if_octets_tx_total{instance='$host'}[$rate]) * 8",
       "legendFormat": "{{interface}} send"
      }
     ]
    },
    {
     "title": "Network Packets / Second",
     "type": "graph",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "pps", "label": "Receive (-) /  Send (+)" }
     ],
     "targets": [
      {
       "expr": "irate(collectd_interface_if_packets_rx_total{instance='$host'}[$rate]) * 8",
       "legendFormat": "{{interface}} receive"
      },
      {
       "expr": "irate(collectd_interface_if_packets_tx_total{instance='$host'}[$rate]) * 8",
       "legendFormat": "{{interface}} send"
      }
     ]
    },
    {
     "title": "Disk Activity / Second",
     "type": "graph",
     "description": "Disk Activity / Second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps", "label": "Read (-) /  Write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_octets_read_total{instance=\"$host\", disk=~\".*\\\\d+\"}[$rate])",
       "legendFormat": "{{disk}} - Read"
      },
      {
       "expr": "irate(collectd_disk_disk_octets_write_total{instance=\"$host\", disk=~\".*\\\\d+\"}[$rate])",
       "legendFormat": "{{disk}} - Write"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "description": "Disk iops per disk",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "iops", "label": "Read (-) /  Write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_ops_read_total{instance=\"$host\", disk=~\".*\\\\d+\"}[$rate])",
       "legendFormat": "{{disk}} - Read"
      },
      {
       "expr": "irate(collectd_disk_disk_ops_write_total{instance=\"$host\", disk=~\".*\\\\d+\"}[$rate])",
       "legendFormat": "{{disk}} - Write"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "graph",
     "description": "Disk space used",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(collectd_df_df_complex{instance=\"$host\", type=\"used\"}) by (df)",
       "legendFormat": "{{df}}"
      }
     ]
    },
    {
     "title": "Disk Queue Length",
     "type": "graph",
     "description": "The amount of requests pending in the disk queue",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_io_time_weighted_io_time_total{instance=\"$host\",disk=~\".*[0-9]+\"}[$rate]) / 1000",
       "legendFormat": "{{disk}}"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "graph",
     "description": "Disk access times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ms", "label": "Read (-) /  Write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_time_read_total{instance=\"$host\",disk=~\".*[0-9]+\"}[$rate])",
       "legendFormat": "{{disk}} - Read"
      },
      {
       "expr": "irate(collectd_disk_disk_time_write_total{instance=\"$host\",disk=~\".*[0-9]+\"}[$rate])",
       "legendFormat": "{{disk}} - Write"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU User",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collectd_cpu_total{instance=\"$host\", type=\"user\"}[$rate])) by (cpu) / sum(rate(collectd_cpu_total{instance=\"$host\"}[$rate])) by (cpu) * 100",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU System",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collectd_cpu_total{instance=\"$host\", type=\"system\"}[$rate])) by (cpu) / sum(rate(collectd_cpu_total{instance=\"$host\"}[$rate])) by (cpu) * 100",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU IOWait",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collectd_cpu_total{instance=\"$host\", type=\"wait\"}[$rate])) by (cpu) / sum(rate(collectd_cpu_total{instance=\"$host\"}[$rate])) by (cpu) * 100",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU SoftIRQ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collectd_cpu_total{instance=\"$host\", type=\"softirq\"}[$rate])) by (cpu) / sum(rate(collectd_cpu_total{instance=\"$host\"}[$rate])) by (cpu) * 100",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU Other",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collectd_cpu_total{instance=\"$host\", type=~\"(interrupt|nice|steal)\"}[$rate])) by (cpu, type)  / ignoring(type) group_left sum(rate(collectd_cpu_total{instance=\"$host\" }[$rate])) by (cpu) * 100",
       "legendFormat": "{{cpu}} - {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Advanced Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches / Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(collectd_contextswitch_total{instance=\"$host\"}[$rate])",
       "legendFormat": "Context Switches"
      }
     ]
    },
    {
     "title": "IRQ Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(collectd_irq_total{instance=\"$host\", irq != \"LOC\"}[$rate])",
       "legendFormat": "{{irq}}"
      }
     ]
    },
    {
     "title": "NUMA Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(collectd_numa_vmpage_action_total{instance=\"$host\"}[$rate])",
       "legendFormat": "{{numa}} - {{type}}"
      }
     ]
    },
    {
     "title": "TCP Connection Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collectd_tcpconns_tcp_connections{instance=\"$host\"}",
       "legendFormat": "{{tcpconns}} - {{type}}"
      }
     ]
    },
    {
     "title": "TCP Connection Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(collectd_protocols_protocol_counter_total{instance=\"$host\"}[$rate])",
       "legendFormat": "{{protocols}} - {{type}}"
      }
     ]
    },
    {
     "title": "Processor Speeds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "collectd_cpufreq{instance=\"$host\"}",
       "legendFormat": "{{cpufreq}}"
      }
     ]
    },
    {
     "title": "Page Cache Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(collectd_vmem_vmpage_faults_majflt_total{instance=\"$host\"}[$rate])",
       "legendFormat": "Major fault"
      },
      {
       "expr": "rate(collectd_vmem_vmpage_faults_minflt_total{instance=\"$host\"}[$rate])",
       "legendFormat": "Minor fault"
      },
      {
       "expr": "rate(collectd_vmem_vmpage_action_total{instance=\"$host\"}[$rate])",
       "legendFormat": "Action - {{vmem}}"
      },
      {
       "expr": "rate(collectd_vmem_vmpage_io_in_total{instance=\"$host\"}[$rate])",
       "legendFormat": "IO read page"
      },
      {
       "expr": "rate(collectd_vmem_vmpage_io_out_total{instance=\"$host\"}[$rate])",
       "legendFormat": "IO write page"
      }
     ]
    },
    {
     "title": "Page Cache Layout",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collectd_vmem_vmpage_number{instance=\"$host\"}",
       "legendFormat": "{{vmem}}"
      }
     ]
    },
    {
     "title": "Process Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "collectd_processes_ps_count_threads{instance=\"$host\"}",
       "legendFormat": "Thread Count"
      },
      {
       "expr": "collectd_processes_ps_count_processes{instance=\"$host\"}",
       "legendFormat": "Process Count"
      },
      {
       "expr": "collectd_processes_ps_state{instance=\"$host\"}",
       "legendFormat": "Process State - {{processes}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic Cassandra Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSTable Count",
     "type": "gauge",
     "description": "Number of sstables on the node",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(mcac_table_live_ss_table_count{instance='$host'})"
      }
     ]
    },
    {
     "title": "Pending Compactions",
     "type": "gauge",
     "description": "Number of pending compactions on the node",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(mcac_compaction_pending_tasks{instance='$host'})"
      }
     ]
    },
    {
     "title": "Connected Clients",
     "type": "gauge",
     "description": "Number of client connections to the node",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(mcac_client_connected_native_clients{instance='$host'})"
      }
     ]
    },
    {
     "title": "GC Activity",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(mcac_jvm_memory_max{instance=\"$host\", memory_type=\"total\"})",
       "legendFormat": "JVM Heap Total"
      },
      {
       "expr": "sum(mcac_jvm_memory_used{instance=\"$host\", memory_type=\"non_heap\"})",
       "legendFormat": "JVM Non-Heap Used"
      },
      {
       "expr": "sum(mcac_jvm_memory_used{instance=\"$host\", memory_type=\"heap\"})",
       "legendFormat": "JVM Heap Used"
      }
     ]
    }
   ]
  }
 ]
}