{
 "title": "Cassandra Datastax - Overview",
 "tags": [
  "cassandra",
  "datastax"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "dc",
    "label": "DataCenter",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{cluster=~\"$cluster\"}, dc)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{}, cluster)"
    }
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{cluster=~\"$cluster\", dc=~\"$dc\"}, rack)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(collectd_collectd_queue_length{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "options": {
    "content": "<a href=\"https://cassandra.apache.org\" target=\"new\"><img src=\"https://cassandra.apache.org/assets/img/logo-white.svg\"/></a>"
   }
  },
  { "type": "text", "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 } },
  {
   "title": "Request Throughputs (Coordinator Perspective)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Request Throughputs",
   "type": "graph",
   "description": "Total Requests Per Cluster, by Request Type",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, request_type) (irate(mcac_client_request_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Error throughputs",
   "type": "graph",
   "description": "Total Timeouts, Failures, Unavailable Rates for each cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, request_type) (irate(mcac_client_request_failures_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "{{request_type}} failures"
    },
    {
     "expr": "sum by (cluster, request_type) (irate(mcac_client_request_timeouts_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "{{request_type}} timeouts"
    },
    {
     "expr": "sum by (cluster, request_type) (irate(mcac_client_request_unavailables_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "{{request_type}} unavailable errors"
    },
    {
     "expr": "sum by (cluster, request_type) (irate(mcac_client_request_unfinished_commit_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "{{request_type}} unfinished commit errors"
    },
    {
     "expr": "sum by (cluster, request_type) (irate(mcac_client_request_condition_not_met_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "{{request_type}} condition not met errors"
    },
    {
     "expr": "sum by (cluster, request_type) (irate(mcac_client_request_contention_histogram_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "{{request_type}} contention histogram errors"
    }
   ]
  },
  {
   "title": "Read / Write Distribution",
   "type": "gauge",
   "description": "Part of reads in the total of standard requests (Reads+Writes). CAS, Views, ... operations are ignored.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster, request_type) (irate(mcac_client_request_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", request_type=\"read\"}[1m])) / ignoring (request_type) (sum by (cluster, request_type) (irate(mcac_client_request_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", request_type=\"read\"}[1m])) + ignoring (request_type) sum by (cluster, request_type) (irate(mcac_client_request_latency_total{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", request_type=\"write\"}[1m])))"
    }
   ]
  },
  {
   "title": "Read Latency (98 - 999th percentile)",
   "type": "graph",
   "description": "Read latency for coordinated reads",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.98, sum(irate(mcac_client_request_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", request_type=\"read\"}[5m])) by (le, cluster))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(mcac_client_request_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", request_type=\"read\"}[5m])) by (le, cluster))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(mcac_client_request_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", request_type=\"read\"}[5m])) by (le, cluster))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "Write Latency (98th - p999 Percentile)",
   "type": "graph",
   "description": "Write latency for coordinated writes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.98, sum(irate(mcac_client_request_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", request_type=\"write\"}[5m])) by (le, cluster))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(mcac_client_request_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", request_type=\"write\"}[5m])) by (le, cluster))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(mcac_client_request_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", request_type=\"write\"}[5m])) by (le, cluster))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "Other Latencies",
   "type": "graph",
   "description": "Other p99 latencies for coordinated requests",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(mcac_client_request_latency_bucket{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", request_type!~\"write|read|.*-.*\"}[5m])) by (le, request_type, cluster))",
     "legendFormat": "p99 {{request_type}}"
    }
   ]
  },
  { "title": "Nodes Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Nodes Status",
   "type": "grafana-polystat-panel",
   "description": "Nodes Status uses Internal/Gossip activity. Be mindful that if Native or Thrift protocol are disabled, the nodes won't be reachable, and still marked up",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "max by (cluster, dc, rack, instance) (changes(mcac_thread_pools_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", pool_name=\"gossip_stage\"}[2m:30s])) > bool 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes Count",
   "type": "stat",
   "description": "Nodes up and down in the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (cluster) (max by (cluster, dc, rack, instance) (collectd_collectd_queue_length{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}))",
     "legendFormat": "Total Number Of Nodes"
    }
   ]
  },
  {
   "title": "Nodes Status History",
   "type": "graph",
   "description": "Nodes up and down in the cluster per protocol/activity",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (cluster) (max by (cluster, dc, rack, instance) (collectd_collectd_queue_length{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}))",
     "legendFormat": "Total Number Of Nodes"
    },
    {
     "expr": "sum by (cluster) (max by (cluster, datacenter, rack, instance) (changes(mcac_thread_pools_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", pool_name=\"native\"}[2m:30s])) > bool 0)",
     "legendFormat": "Nodes Coordinating Requests (Native protocol)"
    },
    {
     "expr": "sum by (cluster) (max by (cluster, datacenter, rack, instance) (changes(mcac_thread_pools_completed_tasks{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", pool_name=\"gossip_stage\"}[2m:30s])) > bool 0)",
     "legendFormat": "Nodes With Internal Activity (Gossip protocol)"
    }
   ]
  },
  { "title": "Data Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk Space Usage",
   "type": "table-old",
   "description": "Disk space used ordered (fullest disks first)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "min by (instance, df) (1-(collectd_df_df_complex{df!~\".*lxcfs.*\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", type=\"free\"}\n        / ignoring (type) (collectd_df_df_complex{df!~\".*lxcfs.*\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", type=\"used\"}\n          + ignoring (type) collectd_df_df_complex{df!~\".*lxcfs.*\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", type=\"reserved\"}\n          + ignoring (type) collectd_df_df_complex{df!~\".*lxcfs.*\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\", type=\"free\"}))\n        )",
     "legendFormat": "{{cluster}}-{{instance}} --> {{df}}"
    }
   ]
  },
  {
   "title": "Cassandra cluster Data Size",
   "type": "graph",
   "description": "Total sizes of the data on distinct nodes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (mcac_table_live_disk_space_used_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "Live space - {{cluster}}"
    },
    {
     "expr": "sum by (cluster) (mcac_table_total_disk_space_used_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "Total space - {{cluster}}"
    }
   ]
  },
  {
   "title": "SSTable Count",
   "type": "graph",
   "description": "SSTable Count Max and Average per table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (cluster, keyspace, table) (mcac_table_live_ss_table_count{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "Table - {{keyspace}}.{{table}}"
    },
    {
     "expr": "max by (cluster) (mcac_table_live_ss_table_count{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "Max in cluster - {{cluster}}"
    }
   ]
  },
  {
   "title": "Pending Compactions",
   "type": "graph",
   "description": "Maximum pending compactions on any node in the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (mcac_table_pending_compactions{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (mcac_table_pending_compactions{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (mcac_table_pending_compactions{cluster=~\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Pending Compactions per Table",
   "type": "graph",
   "description": "Maximum pending compactions per table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (cluster, keyspace, table) (mcac_table_pending_compactions{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "max for {{keyspace}}.{{table}}"
    }
   ]
  },
  { "title": "Cassandra Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Pending Tasks",
   "type": "graph",
   "description": "Cluster wide pending threads, by thread pool name",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (mcac_thread_pools_pending_tasks{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "{{cluster}} - pending {{pool_name}}"
    }
   ]
  },
  {
   "title": "Blocked Tasks",
   "type": "graph",
   "description": "Cluster wide blocked threads, by thread pool name",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (mcac_thread_pools_total_blocked_tasks_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "{{cluster}} - blocked {{pool_name}}"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "graph",
   "description": "Dropped messages rate summed by message type and cluster",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, message_type) (mcac_dropped_message_dropped_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "{{cluster}} - dropped {{message_type}}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "graph",
   "description": "active threads summed per cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (mcac_thread_pools_active_tasks{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "{{cluster}} - active {{pool_name}}"
    }
   ]
  },
  {
   "title": "Hinted Handoff",
   "type": "graph",
   "description": "Sum of hints being handed off per cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (mcac_storage_total_hints_in_progress_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "count"
    }
   ]
  },
  { "title": "Hardware / Operating System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Maximum CPU utilisation (max 100%)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (1 - (sum by (cluster, dc, rack, instance) (irate(collectd_cpu_total{type=\"idle\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m])) / sum by (cluster, dc, rack, instance) (irate(collectd_cpu_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (1 - (sum by (cluster, dc, rack, instance) (irate(collectd_cpu_total{type=\"idle\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m])) / sum by (cluster, dc, rack, instance) (irate(collectd_cpu_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (1 - (sum by (cluster, dc, rack, instance) (irate(collectd_cpu_total{type=\"idle\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m])) / sum by (cluster, dc, rack, instance) (irate(collectd_cpu_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Unix Load (1m rate)",
   "type": "graph",
   "description": "Max Unix load on a node for a cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (collectd_load_shortterm{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (collectd_load_shortterm{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (collectd_load_shortterm{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "description": "Maximum Memory allocated per usage (worst node) - excludes caches, buffers, etc",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min by (cluster) (sum by (cluster, dc, rack, instance) (collectd_memory{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}))",
     "legendFormat": "min memory available"
    },
    {
     "expr": "max by (cluster, memory) (sum by (cluster, dc, rack, instance, memory) (collectd_memory{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}))",
     "legendFormat": "max memory {{memory}}"
    }
   ]
  },
  {
   "title": "Disk Read Thoughput",
   "type": "graph",
   "description": "Disk read throughput",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (irate(collectd_processes_disk_octets_read_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (irate(collectd_processes_disk_octets_read_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (irate(collectd_processes_disk_octets_read_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Disk Write Thoughput",
   "type": "graph",
   "description": "Disk write throughput",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (irate(collectd_processes_disk_octets_write_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (irate(collectd_processes_disk_octets_write_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (irate(collectd_processes_disk_octets_write_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Network In and Out per cluster",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (irate(collectd_interface_if_octets_rx_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "outgoing"
    },
    {
     "expr": "sum by (cluster) (irate(collectd_interface_if_octets_rx_total{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "incoming"
    }
   ]
  },
  { "title": "JVM / Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Application Throughput (% time NOT doing GC)",
   "type": "graph",
   "description": "Percentage of the time the node is *not* doing a GC, thus Cassandra is not stopped for GC",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (1 - (sum by (cluster, dc, rack, instance) (irate(mcac_jvm_gc_time{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m])) / 1000))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (1 - (sum by (cluster, dc, rack, instance) (irate(mcac_jvm_gc_time{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m])) / 1000))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (1 - (sum by (cluster, dc, rack, instance) (irate(mcac_jvm_gc_time{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m])) / 1000))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "description": "Garbage collection duration",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 80 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (irate(mcac_jvm_gc_time{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (irate(mcac_jvm_gc_time{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (irate(mcac_jvm_gc_time{cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"}[1m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Utilisation",
   "type": "graph",
   "description": "Maximum JVM Heap Memory size (worst node) and minimum available heap size",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (cluster)\n        (mcac_jvm_memory_used{memory_type=\"heap\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster)\n        (mcac_jvm_memory_used{memory_type=\"heap\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster)\n        (mcac_jvm_memory_used{memory_type=\"heap\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "min by ( cluster)\n        (mcac_jvm_memory_max{memory_type=\"heap\", cluster=\"$cluster\", dc=~\"$dc\", rack=~\"$rack\", instance=~\"$node\"})",
     "legendFormat": "Heap memory available"
    }
   ]
  }
 ]
}