// Code generated by MockGen. DO NOT EDIT.
// Source: ./controllers/nodectl/nodectl.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nodectl "github.com/ibm/cassandra-operator/controllers/nodectl"
)

// MockNodectl is a mock of Nodectl interface.
type MockNodectl struct {
	ctrl     *gomock.Controller
	recorder *MockNodectlMockRecorder
}

// MockNodectlMockRecorder is the mock recorder for MockNodectl.
type MockNodectlMockRecorder struct {
	mock *MockNodectl
}

// NewMockNodectl creates a new mock instance.
func NewMockNodectl(ctrl *gomock.Controller) *MockNodectl {
	mock := &MockNodectl{ctrl: ctrl}
	mock.recorder = &MockNodectlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodectl) EXPECT() *MockNodectlMockRecorder {
	return m.recorder
}

// ClusterView mocks base method.
func (m *MockNodectl) ClusterView(nodeIP string) (nodectl.ClusterView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterView", nodeIP)
	ret0, _ := ret[0].(nodectl.ClusterView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterView indicates an expected call of ClusterView.
func (mr *MockNodectlMockRecorder) ClusterView(nodeIP interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterView", reflect.TypeOf((*MockNodectl)(nil).ClusterView), nodeIP)
}

// Decommission mocks base method.
func (m *MockNodectl) Decommission(nodeIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decommission", nodeIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decommission indicates an expected call of Decommission.
func (mr *MockNodectlMockRecorder) Decommission(nodeIP interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decommission", reflect.TypeOf((*MockNodectl)(nil).Decommission), nodeIP)
}

// OperationMode mocks base method.
func (m *MockNodectl) OperationMode(nodeIP string) (nodectl.OperationMode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OperationMode", nodeIP)
	ret0, _ := ret[0].(nodectl.OperationMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OperationMode indicates an expected call of OperationMode.
func (mr *MockNodectlMockRecorder) OperationMode(nodeIP interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OperationMode", reflect.TypeOf((*MockNodectl)(nil).OperationMode), nodeIP)
}

// Version mocks base method.
func (m *MockNodectl) Version(nodeIP string) (int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version", nodeIP)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Version indicates an expected call of Version.
func (mr *MockNodectlMockRecorder) Version(nodeIP interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockNodectl)(nil).Version), nodeIP)
}
