// Code generated by MockGen. DO NOT EDIT.
// Source: ./controllers/reaper/reaper.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/ibm/cassandra-operator/api/v1alpha1"
	reaper "github.com/ibm/cassandra-operator/controllers/reaper"
)

// MockReaperClient is a mock of ReaperClient interface.
type MockReaperClient struct {
	ctrl     *gomock.Controller
	recorder *MockReaperClientMockRecorder
}

// MockReaperClientMockRecorder is the mock recorder for MockReaperClient.
type MockReaperClientMockRecorder struct {
	mock *MockReaperClient
}

// NewMockReaperClient creates a new mock instance.
func NewMockReaperClient(ctrl *gomock.Controller) *MockReaperClient {
	mock := &MockReaperClient{ctrl: ctrl}
	mock.recorder = &MockReaperClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaperClient) EXPECT() *MockReaperClientMockRecorder {
	return m.recorder
}

// AddCluster mocks base method.
func (m *MockReaperClient) AddCluster(ctx context.Context, seed string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCluster", ctx, seed)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCluster indicates an expected call of AddCluster.
func (mr *MockReaperClientMockRecorder) AddCluster(ctx, seed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCluster", reflect.TypeOf((*MockReaperClient)(nil).AddCluster), ctx, seed)
}

// ClusterExists mocks base method.
func (m *MockReaperClient) ClusterExists(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterExists", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterExists indicates an expected call of ClusterExists.
func (mr *MockReaperClientMockRecorder) ClusterExists(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterExists", reflect.TypeOf((*MockReaperClient)(nil).ClusterExists), ctx)
}

// Clusters mocks base method.
func (m *MockReaperClient) Clusters(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clusters", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clusters indicates an expected call of Clusters.
func (mr *MockReaperClientMockRecorder) Clusters(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clusters", reflect.TypeOf((*MockReaperClient)(nil).Clusters), ctx)
}

// CreateRepairSchedule mocks base method.
func (m *MockReaperClient) CreateRepairSchedule(ctx context.Context, repair v1alpha1.RepairSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepairSchedule", ctx, repair)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRepairSchedule indicates an expected call of CreateRepairSchedule.
func (mr *MockReaperClientMockRecorder) CreateRepairSchedule(ctx, repair interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepairSchedule", reflect.TypeOf((*MockReaperClient)(nil).CreateRepairSchedule), ctx, repair)
}

// DeleteCluster mocks base method.
func (m *MockReaperClient) DeleteCluster(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockReaperClientMockRecorder) DeleteCluster(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockReaperClient)(nil).DeleteCluster), ctx)
}

// DeleteRepairSchedule mocks base method.
func (m *MockReaperClient) DeleteRepairSchedule(ctx context.Context, repairScheduleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRepairSchedule", ctx, repairScheduleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRepairSchedule indicates an expected call of DeleteRepairSchedule.
func (mr *MockReaperClientMockRecorder) DeleteRepairSchedule(ctx, repairScheduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRepairSchedule", reflect.TypeOf((*MockReaperClient)(nil).DeleteRepairSchedule), ctx, repairScheduleID)
}

// IsRunning mocks base method.
func (m *MockReaperClient) IsRunning(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockReaperClientMockRecorder) IsRunning(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockReaperClient)(nil).IsRunning), ctx)
}

// RepairSchedules mocks base method.
func (m *MockReaperClient) RepairSchedules(ctx context.Context) ([]reaper.RepairSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepairSchedules", ctx)
	ret0, _ := ret[0].([]reaper.RepairSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepairSchedules indicates an expected call of RepairSchedules.
func (mr *MockReaperClientMockRecorder) RepairSchedules(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepairSchedules", reflect.TypeOf((*MockReaperClient)(nil).RepairSchedules), ctx)
}

// RunRepair mocks base method.
func (m *MockReaperClient) RunRepair(ctx context.Context, keyspace, cause string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunRepair", ctx, keyspace, cause)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunRepair indicates an expected call of RunRepair.
func (mr *MockReaperClientMockRecorder) RunRepair(ctx, keyspace, cause interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRepair", reflect.TypeOf((*MockReaperClient)(nil).RunRepair), ctx, keyspace, cause)
}

// SetRepairScheduleState mocks base method.
func (m *MockReaperClient) SetRepairScheduleState(ctx context.Context, repairScheduleID string, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRepairScheduleState", ctx, repairScheduleID, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRepairScheduleState indicates an expected call of SetRepairScheduleState.
func (mr *MockReaperClientMockRecorder) SetRepairScheduleState(ctx, repairScheduleID, active interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRepairScheduleState", reflect.TypeOf((*MockReaperClient)(nil).SetRepairScheduleState), ctx, repairScheduleID, active)
}
