apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-operator-prometheus-configmap
  namespace: {{ .Release.Namespace }}
data: {{ (.Files.Glob "prometheus/prometheus.yaml").AsConfig | nindent 2 }}
