name: Docs

on:
  pull_request:
  release:
    types:
      - created
  push:
    branches:
      - main

jobs:
  checks:
    name: Check Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4 # This is recommended LTS version which includes npm 6.14.10
      - name: Build docs website
        run: |
          npm -v
          node -v
          cd docs
          npm ci
          npm run build
  gh-release:
    if: ${{ github.event_name == 'release' }}
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4 # This is recommended LTS version which includes npm 6.14.10
      - name: Preapre ssh key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.ibm.com >> ~/.ssh/known_hosts
          echo "$SSH_RSA_KEY" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.ibm.com
          HostName github.ibm.com
          IdentityFile ~/.ssh/id_rsa
          EOT
        env:
          SSH_RSA_KEY: ${{ secrets.DOCS_REPO_KEY }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - name: Publish docs website
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: master
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          cd ./docs
          npm ci
          npx docusaurus deploy

